export enum EmailEventType {
  EMAIL_VERIFICATION = 'EMAIL_VERIFICATION',
  PASSWORD_RESET = 'PASSWORD_RESET',
  AUCTION_WON = 'AUCTION_WON',
  AUCTION_STARTING = 'AUCTION_STARTING',
  ORDER_STATUS_CHANGED = 'ORDER_STATUS_CHANGED',
  BALANCE_TOPPED_UP = 'BALANCE_TOPPED_UP',
  BALANCE_WITHDRAWN = 'BALANCE_WITHDRAWN',
  CUSTOM = 'CUSTOM',
}
