import { Injectable, signal, inject, PLATFORM_ID } from '@angular/core';
import { isPlatformBrowser } from '@angular/common';
import { Language } from '../../models/user.model';

type Lang = 'ru' | 'by' | 'en';

const T: Record<Lang, Record<string, string>> = {
  ru: {
    // Header nav
    'nav.catalog': 'Каталог',
    'nav.auctions': 'Аукционы',
    'nav.live': 'Торги',
    'nav.schedule': 'Расписание',
    'nav.about': 'О нас',
    'nav.reviews': 'Отзывы',
    'nav.home': 'Главная',
    'header.search': 'Поиск по марке, модели...',
    'header.login': 'Войти',
    'header.logout': 'Выйти',
    'header.register': 'Регистрация',
    'header.theme.dark': 'Тёмная тема',
    'header.theme.light': 'Светлая тема',
    'header.notifications': 'Уведомления',
    'header.favorites': 'Избранное',
    'header.profile': 'Профиль',
    'toast.login.required': 'Войдите в аккаунт, чтобы увидеть избранное',
    // Cabinet nav
    'cabinet.overview': 'Обзор',
    'cabinet.bids': 'Мои ставки',
    'cabinet.orders': 'Заказы',
    'cabinet.documents': 'Документы',
    'cabinet.balance': 'Баланс',
    'cabinet.watchlist': 'Отслеживаемые',
    'cabinet.calendar': 'Календарь',
    'cabinet.notifications': 'Уведомления',
    'cabinet.calculator': 'Калькулятор',
    'cabinet.settings': 'Настройки',
    'user.verified': 'Верифицирован',
    'user.notVerified': 'Не верифицирован',
    // About page
    'about.badge': 'О компании',
    'about.hero.title': 'RB Motors — <span class="accent-text">ваш путь</span> к автомобилю из Европы',
    'about.hero.desc': 'Мы создали платформу, которая делает покупку автомобилей на европейских аукционах простой, прозрачной и доступной для каждого.',
    'about.why.title': 'Почему выбирают нас',
    'about.why.1.title': 'Ставки в реальном времени',
    'about.why.1.desc': 'Клиент всегда в режиме реального времени отслеживает ставку по своему автомобилю.',
    'about.why.2.title': 'Полная прозрачность сделки',
    'about.why.2.desc': 'Прозрачность на каждом этапе, контроль ценообразования, никаких скрытых платежей.',
    'about.why.3.title': 'Сопровождение до дома',
    'about.why.3.desc': 'Сопровождение автомобиля до указанного адреса, а также помощь с оформлением всей документации вплоть до постановки на учёт.',
    'about.why.4.title': 'Экспертная проверка',
    'about.why.4.desc': 'Наши специалисты проверяют все автомобили перед началом торгов и всегда укажут на «кота в мешке».',
    'about.mission.title': 'Наша миссия',
    'about.mission.p1': 'Предоставить покупателям из СНГ прямой доступ к европейскому авторынку с полным сопровождением — от торгов до доставки автомобиля к порогу.',
    'about.mission.p2': 'Мы объединяем технологии реального времени, прозрачную аукционную механику и профессиональную логистику, чтобы каждый клиент мог приобрести автомобиль по лучшей цене.',
    'about.values.title': 'Наши ценности',
    'about.values.1.title': 'Прозрачность',
    'about.values.1.desc': 'Открытые торги, честные цены, полная история каждого автомобиля',
    'about.values.2.title': 'Скорость',
    'about.values.2.desc': 'Торги в реальном времени, оперативная доставка, быстрая растаможка',
    'about.values.3.title': 'Надёжность',
    'about.values.3.desc': 'Проверенные автомобили, гарантированная доставка, юридическая чистота',
    'about.team.title': 'Команда',
    // Footer
    'footer.desc': 'Платформа онлайн-аукциона автомобилей из Европы. Прозрачные торги в реальном времени.',
    'footer.col.auctions': 'Аукционы',
    'footer.catalog': 'Каталог лотов',
    'footer.live': 'Live торги',
    'footer.ending': 'Завершающиеся скоро',
    'footer.liveTrading': 'Live Trading',
    'footer.calendar': 'Календарь аукционов',
    'footer.col.buyers': 'Покупателям',
    'footer.how.register': 'Как зарегистрироваться',
    'footer.how.bids': 'Как делать ставки',
    'footer.payment': 'Оплата и доставка',
    'footer.customs': 'Растаможка авто',
    'footer.guarantee': 'Гарантии и возврат',
    'footer.col.company': 'Компания',
    'footer.about': 'О нас',
    'footer.faq': 'FAQ',
    'footer.contacts': 'Контакты',
    'footer.jobs': 'Вакансии',
    'footer.blog': 'Блог',
    'footer.partners': 'Партнёры:',
    'footer.copyright': '© 2025–2026 RB Motors. Все права защищены.',
    'footer.privacy': 'Политика конфиденциальности',
    'footer.terms': 'Условия использования',
    'footer.cookies': 'Файлы cookie',
    // Settings
    'settings.title': 'Настройки',
    'settings.profile': 'Профиль',
    'settings.loading': 'Загрузка профиля...',
    'settings.firstName': 'Имя',
    'settings.lastName': 'Фамилия',
    'settings.phone': 'Телефон',
    'settings.saveProfile': 'Сохранить профиль',
    'settings.regional': 'Региональные настройки',
    'settings.country': 'Страна',
    'settings.language': 'Язык',
    'settings.currency': 'Валюта',
    'settings.saveRegional': 'Сохранить региональные настройки',
    'settings.restricted.title': 'Ограниченный регион',
    'settings.restricted.desc': 'По требованию партнёра rbmotors.de, для пользователей из России и Республики Беларусь функционал платформы, включая пополнение баланса, может быть ограничен.',
    'settings.saved.profile': 'Профиль сохранён',
    'settings.saved.regional': 'Региональные настройки сохранены',
    'settings.error.profile': 'Ошибка сохранения профиля',
    'settings.error.regional': 'Ошибка сохранения',
    // Auth
    'auth.login.title': 'Вход в RB Motors',
    'auth.login.subtitle': 'Войдите, чтобы участвовать в торгах',
    'auth.login.forgot': 'Забыли пароль?',
    'auth.login.submit': 'Войти',
    'auth.login.noAccount': 'Нет аккаунта?',
    'auth.login.register': 'Зарегистрироваться',
    'auth.register.title': 'Регистрация в RB Motors',
    'auth.register.subtitle': 'Создайте аккаунт для участия в торгах',
    'auth.register.firstName': 'Имя',
    'auth.register.lastName': 'Фамилия',
    'auth.register.phone': 'Телефон',
    'auth.register.password': 'Пароль',
    'auth.register.confirm': 'Подтвердите пароль',
    'auth.register.submit': 'Зарегистрироваться',
    'auth.register.hasAccount': 'Уже есть аккаунт?',
    'auth.register.login': 'Войти',
    // Live trading page
    'live.noAuctions': 'Сейчас торгов нет',
    'live.loadingSchedule': 'Загрузка расписания...',
    'live.nextAuction': 'Следующий аукцион —',
    'live.noSchedule': 'Расписание пока не объявлено',
    'live.viewSchedule': 'Смотреть расписание',
    'live.tradingFor': 'Торгую за:',
    'live.selectTrader': 'Выберите трейдера',
    'live.today': 'Сегодня в',
    'live.tomorrow': 'Завтра в',
    'time.at': 'в',
    // Auctions schedule page
    'auctions.title': 'Расписание аукционов',
    'auctions.subtitle': 'Выберите день, чтобы увидеть лоты',
    'auctions.live': 'Идёт',
    'auctions.joinBid': 'В торги',
    'auctions.lot1': 'лот',
    'auctions.lot2': 'лота',
    'auctions.lots': 'лотов',
    'auctions.km': 'км',
  },
  by: {
    // Header nav
    'nav.catalog': 'Каталог',
    'nav.auctions': 'Аўкцыёны',
    'nav.live': 'Таргі',
    'nav.schedule': 'Расклад',
    'nav.about': 'Пра нас',
    'nav.reviews': 'Водгукі',
    'nav.home': 'Галоўная',
    'header.search': 'Пошук па марцы, мадэлі...',
    'header.login': 'Увайсці',
    'header.logout': 'Выйсці',
    'header.register': 'Рэгістрацыя',
    'header.theme.dark': 'Цёмная тэма',
    'header.theme.light': 'Светлая тэма',
    'header.notifications': 'Апавяшчэнні',
    'header.favorites': 'Абраныя',
    'header.profile': 'Профіль',
    'toast.login.required': 'Увайдзіце ў акаўнт, каб убачыць абраныя',
    // Cabinet nav
    'cabinet.overview': 'Агляд',
    'cabinet.bids': 'Мае стаўкі',
    'cabinet.orders': 'Заказы',
    'cabinet.documents': 'Дакументы',
    'cabinet.balance': 'Баланс',
    'cabinet.watchlist': 'Адсочваемыя',
    'cabinet.calendar': 'Каляндар',
    'cabinet.notifications': 'Апавяшчэнні',
    'cabinet.calculator': 'Калькулятар',
    'cabinet.settings': 'Налады',
    'user.verified': 'Верыфікаваны',
    'user.notVerified': 'Не верыфікаваны',
    // About page
    'about.badge': 'Пра кампанію',
    'about.hero.title': 'RB Motors — <span class="accent-text">ваш шлях</span> да аўтамабіля з Еўропы',
    'about.hero.desc': 'Мы стварылі платформу, якая робіць куплю аўтамабіляў на еўрапейскіх аўкцыёнах простай, празрыстай і даступнай для кожнага.',
    'about.why.title': 'Чаму выбіраюць нас',
    'about.why.1.title': 'Стаўкі ў рэжыме рэальнага часу',
    'about.why.1.desc': 'Кліент заўсёды ў рэжыме рэальнага часу адсочвае стаўку па сваім аўтамабілі.',
    'about.why.2.title': 'Поўная празрыстасць здзелкі',
    'about.why.2.desc': 'Празрыстасць на кожным этапе, кантроль цэнаўтварэння, ніякіх схаваных плацяжоў.',
    'about.why.3.title': 'Суправаджэнне да дому',
    'about.why.3.desc': 'Суправаджэнне аўтамабіля да паказанага адрасу, а таксама дапамога з афармленнем усёй дакументацыі аж да пастаноўкі на ўлік.',
    'about.why.4.title': 'Экспертная праверка',
    'about.why.4.desc': 'Нашы спецыялісты правяраюць усе аўтамабілі перад пачаткам таргоў і заўсёды ўкажуць на «ката ў мяшку».',
    'about.mission.title': 'Наша місія',
    'about.mission.p1': 'Даць пакупнікам з СНД прамы доступ да еўрапейскага аўтарынку з поўным суправаджэннем — ад таргоў да дастаўкі аўтамабіля да парога.',
    'about.mission.p2': 'Мы аб\'ядноўваем тэхналогіі рэальнага часу, празрыстую аўкцыённую механіку і прафесійную лагістыку, каб кожны кліент мог набыць аўтамабіль па лепшай цане.',
    'about.values.title': 'Нашы каштоўнасці',
    'about.values.1.title': 'Празрыстасць',
    'about.values.1.desc': 'Адкрытыя таргі, сумленныя цэны, поўная гісторыя кожнага аўтамабіля',
    'about.values.2.title': 'Хуткасць',
    'about.values.2.desc': 'Таргі ў рэжыме рэальнага часу, аператыўная дастаўка, хуткае расцамажванне',
    'about.values.3.title': 'Надзейнасць',
    'about.values.3.desc': 'Правераныя аўтамабілі, гарантаваная дастаўка, юрыдычная чысціня',
    'about.team.title': 'Каманда',
    // Footer
    'footer.desc': 'Платформа онлайн-аўкцыёну аўтамабіляў з Еўропы. Празрыстыя таргі ў рэжыме рэальнага часу.',
    'footer.col.auctions': 'Аўкцыёны',
    'footer.catalog': 'Каталог лотаў',
    'footer.live': 'Live таргі',
    'footer.ending': 'Якія завяршаюцца хутка',
    'footer.liveTrading': 'Live Trading',
    'footer.calendar': 'Каляндар аўкцыёнаў',
    'footer.col.buyers': 'Пакупнікам',
    'footer.how.register': 'Як зарэгістравацца',
    'footer.how.bids': 'Як рабіць стаўкі',
    'footer.payment': 'Аплата і дастаўка',
    'footer.customs': 'Расцамажванне аўто',
    'footer.guarantee': 'Гарантыі і вяртанне',
    'footer.col.company': 'Кампанія',
    'footer.about': 'Пра нас',
    'footer.faq': 'FAQ',
    'footer.contacts': 'Кантакты',
    'footer.jobs': 'Вакансіі',
    'footer.blog': 'Блог',
    'footer.partners': 'Партнёры:',
    'footer.copyright': '© 2025–2026 RB Motors. Усе правы абаронены.',
    'footer.privacy': 'Палітыка канфідэнцыяльнасці',
    'footer.terms': 'Умовы выкарыстання',
    'footer.cookies': 'Файлы cookie',
    // Settings
    'settings.title': 'Налады',
    'settings.profile': 'Профіль',
    'settings.loading': 'Загрузка профілю...',
    'settings.firstName': 'Імя',
    'settings.lastName': 'Прозвішча',
    'settings.phone': 'Тэлефон',
    'settings.saveProfile': 'Захаваць профіль',
    'settings.regional': 'Рэгіянальныя налады',
    'settings.country': 'Краіна',
    'settings.language': 'Мова',
    'settings.currency': 'Валюта',
    'settings.saveRegional': 'Захаваць рэгіянальныя налады',
    'settings.restricted.title': 'Абмежаваны рэгіён',
    'settings.restricted.desc': 'Па патрабаванні партнёра rbmotors.de, для карыстальнікаў з Расіі і Рэспублікі Беларусь функцыянал платформы, уключаючы папаўненне балансу, можа быць абмежаваны.',
    'settings.saved.profile': 'Профіль захаваны',
    'settings.saved.regional': 'Рэгіянальныя налады захаваны',
    'settings.error.profile': 'Памылка захавання профілю',
    'settings.error.regional': 'Памылка захавання',
    // Auth
    'auth.login.title': 'Уваход у RB Motors',
    'auth.login.subtitle': 'Увайдзіце, каб удзельнічаць у таргах',
    'auth.login.forgot': 'Забылі пароль?',
    'auth.login.submit': 'Увайсці',
    'auth.login.noAccount': 'Няма акаўнту?',
    'auth.login.register': 'Зарэгістравацца',
    'auth.register.title': 'Рэгістрацыя ў RB Motors',
    'auth.register.subtitle': 'Стварыце акаўнт для ўдзелу ў таргах',
    'auth.register.firstName': 'Імя',
    'auth.register.lastName': 'Прозвішча',
    'auth.register.phone': 'Тэлефон',
    'auth.register.password': 'Пароль',
    'auth.register.confirm': 'Пацвердзіце пароль',
    'auth.register.submit': 'Зарэгістравацца',
    'auth.register.hasAccount': 'Ужо ёсць акаўнт?',
    'auth.register.login': 'Увайсці',
    // Live trading page
    'live.noAuctions': 'Зараз таргоў няма',
    'live.loadingSchedule': 'Загрузка раскладу...',
    'live.nextAuction': 'Наступны аўкцыён —',
    'live.noSchedule': 'Расклад пакуль не аб\'яўлены',
    'live.viewSchedule': 'Глядзець расклад',
    'live.tradingFor': 'Таргуюся за:',
    'live.selectTrader': 'Выберыце трэйдара',
    'live.today': 'Сёння ў',
    'live.tomorrow': 'Заўтра ў',
    'time.at': 'ў',
    // Auctions schedule page
    'auctions.title': 'Расклад аўкцыёнаў',
    'auctions.subtitle': 'Выберыце дзень, каб убачыць лоты',
    'auctions.live': 'Ідзе',
    'auctions.joinBid': 'У таргі',
    'auctions.lot1': 'лот',
    'auctions.lot2': 'лоты',
    'auctions.lots': 'лотаў',
    'auctions.km': 'км',
  },
  en: {
    // Header nav
    'nav.catalog': 'Catalog',
    'nav.auctions': 'Auctions',
    'nav.live': 'Live Bids',
    'nav.schedule': 'Schedule',
    'nav.about': 'About',
    'nav.reviews': 'Reviews',
    'nav.home': 'Home',
    'header.search': 'Search by make, model...',
    'header.login': 'Log in',
    'header.logout': 'Log out',
    'header.register': 'Register',
    'header.theme.dark': 'Dark mode',
    'header.theme.light': 'Light mode',
    'header.notifications': 'Notifications',
    'header.favorites': 'Favourites',
    'header.profile': 'Profile',
    'toast.login.required': 'Log in to see your favourites',
    // Cabinet nav
    'cabinet.overview': 'Overview',
    'cabinet.bids': 'My Bids',
    'cabinet.orders': 'Orders',
    'cabinet.documents': 'Documents',
    'cabinet.balance': 'Balance',
    'cabinet.watchlist': 'Watchlist',
    'cabinet.calendar': 'Calendar',
    'cabinet.notifications': 'Notifications',
    'cabinet.calculator': 'Calculator',
    'cabinet.settings': 'Settings',
    'user.verified': 'Verified',
    'user.notVerified': 'Not Verified',
    // About page
    'about.badge': 'About Us',
    'about.hero.title': 'RB Motors — <span class="accent-text">your gateway</span> to European cars',
    'about.hero.desc': 'We built a platform that makes buying cars at European auctions simple, transparent, and accessible to everyone.',
    'about.why.title': 'Why choose us',
    'about.why.1.title': 'Real-time bidding',
    'about.why.1.desc': 'Clients always track their bid on a vehicle in real time.',
    'about.why.2.title': 'Full transaction transparency',
    'about.why.2.desc': 'Transparency at every step, controlled pricing, no hidden fees.',
    'about.why.3.title': 'Delivery to your door',
    'about.why.3.desc': 'We accompany the vehicle to the specified address and assist with all paperwork, including vehicle registration.',
    'about.why.4.title': 'Expert inspection',
    'about.why.4.desc': 'Our specialists inspect every vehicle before bidding begins and will always flag any hidden issues.',
    'about.mission.title': 'Our Mission',
    'about.mission.p1': 'To give CIS buyers direct access to the European car market with full support — from bidding to doorstep delivery.',
    'about.mission.p2': 'We combine real-time technology, transparent auction mechanics, and professional logistics so every client can buy a car at the best price.',
    'about.values.title': 'Our Values',
    'about.values.1.title': 'Transparency',
    'about.values.1.desc': 'Open auctions, fair prices, complete history of every vehicle',
    'about.values.2.title': 'Speed',
    'about.values.2.desc': 'Real-time bidding, fast delivery, swift customs clearance',
    'about.values.3.title': 'Reliability',
    'about.values.3.desc': 'Verified vehicles, guaranteed delivery, legal clarity',
    'about.team.title': 'Team',
    // Footer
    'footer.desc': 'Online car auction platform from Europe. Transparent real-time bidding.',
    'footer.col.auctions': 'Auctions',
    'footer.catalog': 'Lot Catalog',
    'footer.live': 'Live Bidding',
    'footer.ending': 'Ending Soon',
    'footer.liveTrading': 'Live Trading',
    'footer.calendar': 'Auction Calendar',
    'footer.col.buyers': 'For Buyers',
    'footer.how.register': 'How to Register',
    'footer.how.bids': 'How to Bid',
    'footer.payment': 'Payment & Delivery',
    'footer.customs': 'Car Customs Clearance',
    'footer.guarantee': 'Guarantees & Returns',
    'footer.col.company': 'Company',
    'footer.about': 'About Us',
    'footer.faq': 'FAQ',
    'footer.contacts': 'Contacts',
    'footer.jobs': 'Careers',
    'footer.blog': 'Blog',
    'footer.partners': 'Partners:',
    'footer.copyright': '© 2025–2026 RB Motors. All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Use',
    'footer.cookies': 'Cookies',
    // Settings
    'settings.title': 'Settings',
    'settings.profile': 'Profile',
    'settings.loading': 'Loading profile...',
    'settings.firstName': 'First Name',
    'settings.lastName': 'Last Name',
    'settings.phone': 'Phone',
    'settings.saveProfile': 'Save Profile',
    'settings.regional': 'Regional Settings',
    'settings.country': 'Country',
    'settings.language': 'Language',
    'settings.currency': 'Currency',
    'settings.saveRegional': 'Save Regional Settings',
    'settings.restricted.title': 'Restricted Region',
    'settings.restricted.desc': 'At the request of our partner rbmotors.de, certain platform features, including balance top-up, may be restricted for users from Russia and the Republic of Belarus.',
    'settings.saved.profile': 'Profile saved',
    'settings.saved.regional': 'Regional settings saved',
    'settings.error.profile': 'Error saving profile',
    'settings.error.regional': 'Error saving settings',
    // Auth
    'auth.login.title': 'Log in to RB Motors',
    'auth.login.subtitle': 'Log in to start bidding',
    'auth.login.forgot': 'Forgot password?',
    'auth.login.submit': 'Log In',
    'auth.login.noAccount': 'No account?',
    'auth.login.register': 'Register',
    'auth.register.title': 'Create an RB Motors account',
    'auth.register.subtitle': 'Create an account to participate in auctions',
    'auth.register.firstName': 'First Name',
    'auth.register.lastName': 'Last Name',
    'auth.register.phone': 'Phone',
    'auth.register.password': 'Password',
    'auth.register.confirm': 'Confirm Password',
    'auth.register.submit': 'Register',
    'auth.register.hasAccount': 'Already have an account?',
    'auth.register.login': 'Log In',
    // Live trading page
    'live.noAuctions': 'No active auctions',
    'live.loadingSchedule': 'Loading schedule...',
    'live.nextAuction': 'Next auction —',
    'live.noSchedule': 'No schedule announced yet',
    'live.viewSchedule': 'View schedule',
    'live.tradingFor': 'Bidding for:',
    'live.selectTrader': 'Select trader',
    'live.today': 'Today at',
    'live.tomorrow': 'Tomorrow at',
    'time.at': 'at',
    // Auctions schedule page
    'auctions.title': 'Auction Schedule',
    'auctions.subtitle': 'Select a day to view lots',
    'auctions.live': 'Live',
    'auctions.joinBid': 'Join Bid',
    'auctions.lot1': 'lot',
    'auctions.lot2': 'lots',
    'auctions.lots': 'lots',
    'auctions.km': 'km',
  },
};

@Injectable({ providedIn: 'root' })
export class LanguageService {
  private readonly platformId = inject(PLATFORM_ID);
  readonly lang = signal<Lang>('ru');

  init(): void {
    if (!isPlatformBrowser(this.platformId)) return;
    const saved = localStorage.getItem('lang') as Lang | null;
    if (saved === 'ru' || saved === 'by' || saved === 'en') {
      this.lang.set(saved);
    }
  }

  setLang(l: Language | Lang): void {
    const code = l as Lang;
    this.lang.set(code);
    if (isPlatformBrowser(this.platformId)) {
      localStorage.setItem('lang', code);
    }
  }

  t(key: string): string {
    return T[this.lang()][key] ?? key;
  }
}
