import { Injectable, signal, inject, PLATFORM_ID } from '@angular/core';
import { isPlatformBrowser } from '@angular/common';
import { Language } from '../../models/user.model';

type Lang = 'ru' | 'by' | 'en';

const T: Record<Lang, Record<string, string>> = {
  ru: {
    // Header nav
    'nav.catalog': 'Каталог',
    'nav.auctions': 'Аукционы',
    'nav.live': 'Торги',
    'nav.schedule': 'Расписание',
    'nav.about': 'О нас',
    'nav.reviews': 'Отзывы',
    'nav.home': 'Главная',
    'header.search': 'Поиск по марке, модели...',
    'header.login': 'Войти',
    'header.logout': 'Выйти',
    'header.register': 'Регистрация',
    'header.theme.dark': 'Тёмная тема',
    'header.theme.light': 'Светлая тема',
    'header.notifications': 'Уведомления',
    'header.favorites': 'Избранное',
    'header.profile': 'Профиль',
    'toast.login.required': 'Войдите в аккаунт, чтобы увидеть избранное',
    // Cabinet nav
    'cabinet.overview': 'Обзор',
    'cabinet.bids': 'Мои ставки',
    'cabinet.orders': 'Заказы',
    'cabinet.documents': 'Документы',
    'cabinet.balance': 'Баланс',
    'cabinet.watchlist': 'Отслеживаемые',
    'cabinet.calendar': 'Календарь',
    'cabinet.notifications': 'Уведомления',
    'cabinet.calculator': 'Калькулятор',
    'cabinet.settings': 'Настройки',
    'user.verified': 'Верифицирован',
    'user.notVerified': 'Не верифицирован',
    // About page
    'about.badge': 'О компании',
    'about.hero.title': 'RB Motors — <span class="accent-text">ваш путь</span> к автомобилю из Европы',
    'about.hero.desc': 'Мы создали платформу, которая делает покупку автомобилей на европейских аукционах простой, прозрачной и доступной для каждого.',
    'about.why.title': 'Почему выбирают нас',
    'about.why.1.title': 'Ставки в реальном времени',
    'about.why.1.desc': 'Клиент всегда в режиме реального времени отслеживает ставку по своему автомобилю.',
    'about.why.2.title': 'Полная прозрачность сделки',
    'about.why.2.desc': 'Прозрачность на каждом этапе, контроль ценообразования, никаких скрытых платежей.',
    'about.why.3.title': 'Сопровождение до дома',
    'about.why.3.desc': 'Сопровождение автомобиля до указанного адреса, а также помощь с оформлением всей документации вплоть до постановки на учёт.',
    'about.why.4.title': 'Экспертная проверка',
    'about.why.4.desc': 'Наши специалисты проверяют все автомобили перед началом торгов и всегда укажут на «кота в мешке».',
    'about.mission.title': 'Наша миссия',
    'about.mission.p1': 'Предоставить покупателям из СНГ прямой доступ к европейскому авторынку с полным сопровождением — от торгов до доставки автомобиля к порогу.',
    'about.mission.p2': 'Мы объединяем технологии реального времени, прозрачную аукционную механику и профессиональную логистику, чтобы каждый клиент мог приобрести автомобиль по лучшей цене.',
    'about.values.title': 'Наши ценности',
    'about.values.1.title': 'Прозрачность',
    'about.values.1.desc': 'Открытые торги, честные цены, полная история каждого автомобиля',
    'about.values.2.title': 'Скорость',
    'about.values.2.desc': 'Торги в реальном времени, оперативная доставка, быстрая растаможка',
    'about.values.3.title': 'Надёжность',
    'about.values.3.desc': 'Проверенные автомобили, гарантированная доставка, юридическая чистота',
    'about.team.title': 'Команда',
    // Footer
    'footer.desc': 'Платформа онлайн-аукциона автомобилей из Европы. Прозрачные торги в реальном времени.',
    'footer.col.auctions': 'Аукционы',
    'footer.catalog': 'Каталог лотов',
    'footer.live': 'Live торги',
    'footer.ending': 'Завершающиеся скоро',
    'footer.liveTrading': 'Live Trading',
    'footer.calendar': 'Календарь аукционов',
    'footer.col.buyers': 'Покупателям',
    'footer.how.register': 'Как зарегистрироваться',
    'footer.how.bids': 'Как делать ставки',
    'footer.payment': 'Оплата и доставка',
    'footer.customs': 'Растаможка авто',
    'footer.guarantee': 'Гарантии и возврат',
    'footer.col.company': 'Компания',
    'footer.about': 'О нас',
    'footer.faq': 'FAQ',
    'footer.contacts': 'Контакты',
    'footer.jobs': 'Вакансии',
    'footer.blog': 'Блог',
    'footer.partners': 'Партнёры:',
    'footer.copyright': '© 2025–2026 RB Motors. Все права защищены.',
    'footer.privacy': 'Политика конфиденциальности',
    'footer.terms': 'Условия использования',
    'footer.cookies': 'Файлы cookie',
    // Settings
    'settings.title': 'Настройки',
    'settings.profile': 'Профиль',
    'settings.loading': 'Загрузка профиля...',
    'settings.firstName': 'Имя',
    'settings.lastName': 'Фамилия',
    'settings.phone': 'Телефон',
    'settings.saveProfile': 'Сохранить профиль',
    'settings.regional': 'Региональные настройки',
    'settings.country': 'Страна',
    'settings.language': 'Язык',
    'settings.currency': 'Валюта',
    'settings.saveRegional': 'Сохранить региональные настройки',
    'settings.restricted.title': 'Ограниченный регион',
    'settings.restricted.desc': 'По требованию партнёра rbmotors.de, для пользователей из России и Республики Беларусь функционал платформы, включая пополнение баланса, может быть ограничен.',
    'settings.saved.profile': 'Профиль сохранён',
    'settings.saved.regional': 'Региональные настройки сохранены',
    'settings.error.profile': 'Ошибка сохранения профиля',
    'settings.error.regional': 'Ошибка сохранения',
    // Auth
    'auth.login.title': 'Вход в RB Motors',
    'auth.login.subtitle': 'Войдите, чтобы участвовать в торгах',
    'auth.login.forgot': 'Забыли пароль?',
    'auth.login.submit': 'Войти',
    'auth.login.noAccount': 'Нет аккаунта?',
    'auth.login.register': 'Зарегистрироваться',
    'auth.register.title': 'Регистрация в RB Motors',
    'auth.register.subtitle': 'Создайте аккаунт для участия в торгах',
    'auth.register.firstName': 'Имя',
    'auth.register.lastName': 'Фамилия',
    'auth.register.phone': 'Телефон',
    'auth.register.password': 'Пароль',
    'auth.register.confirm': 'Подтвердите пароль',
    'auth.register.submit': 'Зарегистрироваться',
    'auth.register.hasAccount': 'Уже есть аккаунт?',
    'auth.register.login': 'Войти',
    // Live trading page
    'live.noAuctions': 'Сейчас торгов нет',
    'live.loadingSchedule': 'Загрузка расписания...',
    'live.nextAuction': 'Следующий аукцион —',
    'live.noSchedule': 'Расписание пока не объявлено',
    'live.viewSchedule': 'Смотреть расписание',
    'live.tradingFor': 'Торгую за:',
    'live.selectTrader': 'Выберите трейдера',
    'live.today': 'Сегодня в',
    'live.tomorrow': 'Завтра в',
    'time.at': 'в',
    // Auctions schedule page
    'auctions.title': 'Расписание аукционов',
    'auctions.subtitle': 'Выберите день, чтобы увидеть лоты',
    'auctions.live': 'Идёт',
    'auctions.joinBid': 'В торги',
    'auctions.lot1': 'лот',
    'auctions.lot2': 'лота',
    'auctions.lots': 'лотов',
    'auctions.km': 'км',
    // Shared fuel types
    'fuel.petrol': 'Бензин',
    'fuel.diesel': 'Дизель',
    'fuel.hybrid': 'Гибрид',
    'fuel.electric': 'Электро',
    'fuel.lpg': 'Газ',
    'fuel.other': 'Другое',
    // Shared transmissions
    'trans.automatic': 'Автомат',
    'trans.manual': 'Механика',
    // Home page
    'home.hero.title': 'Найдите автомобиль мечты',
    'home.hero.subtitle': 'Автомобили с европейских аукционов BCA Europe',
    'home.hero.subtitleCount': 'Более {n} автомобилей с европейских аукционов',
    'home.hero.browse': 'Смотреть каталог',
    'home.popular': 'Популярное:',
    'home.auctions.title': 'Автомобили на аукционе',
    'home.auctions.count': '{n} автомобилей в каталоге',
    'home.brands': 'Популярные марки',
    'home.startingPrice': 'Стартовая цена',
    'home.km': 'км',
    'home.seeAll': 'Смотреть все автомобили',
    'home.recent': 'Недавно добавленные',
    'home.recentSub': 'Новые лоты из BCA Europe',
    'home.seeAllCars': 'Все автомобили',
    'home.details': 'Подробнее',
    'home.loading': 'Загрузка...',
    'home.noLots': 'Пока нет лотов в базе.',
    'home.cta.title': 'Готовы купить авто с европейского аукциона?',
    'home.cta.desc': 'Зарегистрируйтесь, пополните баланс и начните торговаться уже сегодня. Мы возьмём на себя доставку и растаможку.',
    'home.cta.create': 'Создать аккаунт',
    'home.cta.browse': 'Смотреть каталог',
    'home.cta.verified': 'Проверенные авто',
    'home.cta.guarantee': 'Гарантия сделки',
    'home.cta.delivery': 'Доставка под ключ',
    'home.how': 'Как это работает',
    'home.step1.title': 'Регистрация',
    'home.step1.desc': 'Создайте аккаунт и пройдите верификацию',
    'home.step2.title': 'Пополните баланс',
    'home.step2.desc': 'Внесите депозит для участия в торгах',
    'home.step3.title': 'Выберите авто',
    'home.step3.desc': 'Найдите автомобиль в каталоге или на live-торгах',
    'home.step4.title': 'Сделайте ставку',
    'home.step4.desc': 'Участвуйте в аукционе в реальном времени',
    'home.step5.title': 'Оплатите лот',
    'home.step5.desc': 'После победы оплатите автомобиль',
    'home.step6.title': 'Доставка и растаможка',
    'home.step6.desc': 'Мы доставим и растаможим авто для вас',
    'home.step7.title': 'Получите авто',
    'home.step7.desc': 'Заберите автомобиль по вашему адресу',
    // Catalog page
    'catalog.title': 'Каталог автомобилей',
    'catalog.lots': 'лотов',
    'catalog.filters': 'Фильтры',
    'catalog.reset': 'Сбросить',
    'catalog.brand': 'Марка',
    'catalog.allBrands': 'Все марки',
    'catalog.model': 'Модель',
    'catalog.modelPlaceholder': 'Начните вводить модель...',
    'catalog.year': 'Год выпуска',
    'catalog.price': 'Цена, EUR',
    'catalog.fuel': 'Топливо',
    'catalog.allFuels': 'Все',
    'catalog.trans': 'Коробка передач',
    'catalog.mileage': 'Пробег, км',
    'catalog.engine': 'Объём двигателя, см³',
    'catalog.find': 'Найти',
    'catalog.loading': 'Загрузка...',
    'catalog.notFound': 'Лоты не найдены. Попробуйте изменить фильтры или запустить парсинг в настройках.',
    'catalog.km': 'км',
    'catalog.ps': 'л.с.',
    'catalog.currentBid': 'Текущая ставка',
    'catalog.startingPrice': 'Стартовая цена',
    'catalog.loadingMore': 'Загрузка...',
    'catalog.allLoaded': 'Все лоты загружены',
    'catalog.from': 'От',
    'catalog.to': 'До',
    'sort.new': 'Новые',
    'sort.upcoming': 'Ближайшие аукционы',
    'sort.priceAsc': 'Цена ↑',
    'sort.priceDesc': 'Цена ↓',
    'sort.yearDesc': 'Год ↓',
    'sort.mileageAsc': 'Пробег ↑',
    // Lot detail spec labels
    'spec.power': 'Мощность',
    'spec.fuel': 'Топливо',
    'spec.mileage': 'Пробег',
    'spec.year': 'Год',
    'spec.transmission': 'КПП',
    'spec.color': 'Цвет',
    'spec.type': 'Тип',
    'spec.doors': 'Двери',
    'spec.seats': 'Места',
    'spec.gears': 'Передачи',
    'spec.volume': 'Объем',
    'spec.emission': 'Эмиссия',
    'spec.owners': 'Владельцев',
    'spec.keys': 'Ключей',
    'spec.ps': 'л.с.',
    'spec.kw': 'кВт',
    'spec.km': 'км',
    // Lot detail page
    'lot.loading': 'Загрузка...',
    'lot.notFound': 'Лот не найден',
    'lot.backToCatalog': 'Вернуться в каталог',
    'lot.home': 'Главная',
    'lot.catalog': 'Каталог',
    'lot.noPhoto': 'Нет фото',
    'lot.gallery.all': 'Все фото',
    'lot.gallery.exterior': 'Экстерьер',
    'lot.gallery.interior': 'Интерьер',
    'lot.gallery.damage': 'Повреждения',
    'lot.specs': 'Характеристики',
    'lot.pending': 'Лот осматривается экспертами, информация появится позже',
    'lot.equipment': 'Комплектация',
    'lot.showAll': 'Показать все ({n})',
    'lot.showLess': 'Скрыть',
    'lot.serviceHistory': 'История обслуживания',
    'lot.historyDate': 'Дата',
    'lot.historyMileage': 'Пробег',
    'lot.historyDesc': 'Описание',
    'lot.historyCompany': 'Компания',
    'lot.accident': 'Авария / Повреждения',
    'lot.damagePhotos': 'Фото повреждений',
    'lot.body': 'Кузов',
    'lot.interior': 'Салон',
    'lot.tires': 'Шины / Колесные диски',
    'lot.tiresPosition': 'Позиция',
    'lot.tiresDepth': 'Глубина протектора',
    'lot.tiresSize': 'Размер',
    'lot.stoneChips': 'Сколы / Ветровое стекло',
    'lot.seats': 'Сиденья',
    'lot.general': 'Общая информация',
    'lot.parking': 'Стоянка',
    'lot.condition': 'Состояние',
    'lot.startingPrice': 'Стартовая цена',
    'lot.pricePending': 'Ожидается',
    'lot.buyNow': 'Цена выкупа',
    'lot.currentBid': 'Текущая ставка',
    'lot.watching': 'наблюдают',
    'lot.ended': 'Торги завершены',
    'lot.winning': 'Вы лидируете!',
    'lot.outbid': 'Ваша ставка перебита',
    'lot.autobidActive': 'Авто-ставка до {n} {cur}',
    'lot.bidSuccess': 'Ставка принята!',
    'lot.processing': 'Обработка...',
    'lot.makeBid': 'Сделать ставку',
    'lot.bidFor': 'Ставка за {name}',
    'lot.autoBidLabel': 'Авто-ставка (Pre-bid)',
    'lot.autoBidHint': 'Система автоматически перебивает конкурентов до указанного лимита.',
    'lot.autoBidPlaceholder': 'Лимит от {n}',
    'lot.autoBidSet': 'Установить',
    'lot.minPayment': 'Минимальный платёж',
    'lot.origin': 'Производство:',
    'lot.seller': 'Продавец:',
    'lot.inFavorite': 'В избранном',
    'lot.addFavorite': 'В избранное',
    'lot.tradingFor': 'Торгую за:',
    'lot.selectTrader': '— Выберите клиента —',
    'lot.loginPrompt': 'чтобы сделать ставку',
    'lot.loginLink': 'Войдите',
    'lot.bidHistory': 'Последние ставки',
    'lot.autoBidTooltip': 'Авто-ставка',
    'lot.brokerNotice': 'Торги ведёт ваш брокер. Добавьте лот в избранное — брокер сделает ставку.',
    'lot.minBidError': 'Минимальная ставка: €{n}',
    'lot.noResponse': 'Нет ответа от сервера. Попробуйте снова.',
    'lot.minAutoBidError': 'Авто-ставка должна быть не менее €{n}',
    // Contacts page
    'contacts.badge': 'Контакты',
    'contacts.title': 'Свяжитесь с нами',
    'contacts.subtitle': 'Мы всегда на связи и готовы помочь',
    'contacts.phone': 'Телефон',
    'contacts.hours': 'Время работы',
    'contacts.hoursValue': 'Пн — Пт: 9:00 — 18:00',
    'contacts.formTitle': 'Напишите нам',
    'contacts.name': 'Имя',
    'contacts.namePlaceholder': 'Ваше имя',
    'contacts.messageLabel': 'Сообщение',
    'contacts.messagePlaceholder': 'Ваше сообщение...',
    'contacts.submit': 'Отправить',
    // Reviews page
    'reviews.badge': 'Отзывы клиентов',
    'reviews.title': 'Что говорят <span class="accent-text">наши клиенты</span>',
    'reviews.subtitle': 'Реальные отзывы покупателей, которые приобрели автомобили через нашу платформу. Мы ценим каждое мнение.',
    'reviews.promo.title': 'Акция: видео-отзыв = 100 USDT',
    'reviews.promo.text': 'Запиши видео-отзыв со своим авто, купленным через RB Motors, в апреле 2026 и получи кешбек <strong>100 USDT</strong> на баланс.',
    'reviews.promo.countdownLabel': 'До старта акции:',
    'reviews.promo.days': 'дн',
    'reviews.promo.hours': 'ч',
    'reviews.promo.minutes': 'мин',
    'reviews.promo.seconds': 'сек',
    'reviews.promo.btn': 'Подробнее',
    'reviews.loading': 'Загрузка отзывов...',
    'reviews.totalCount': '{n} отзывов',
    'reviews.leaveReview': 'Оставить отзыв',
    'reviews.loginToReview': 'Войдите, чтобы оставить отзыв',
    'reviews.loadMore': 'Показать ещё',
    'reviews.loadingMore': 'Загрузка...',
    'reviews.noReviews': 'Отзывов пока нет. Будьте первым!',
    'reviews.error.load': 'Не удалось загрузить отзывы',
    'reviews.modal.title': 'Оставить отзыв',
    'reviews.modal.success.title': 'Спасибо за отзыв!',
    'reviews.modal.success.text': 'Ваш отзыв успешно опубликован.',
    'reviews.modal.ratingLabel': 'Ваша оценка',
    'reviews.modal.nameLabel': 'Ваше имя',
    'reviews.modal.namePlaceholder': 'Как вас подписать? (необязательно)',
    'reviews.modal.textLabel': 'Ваш отзыв',
    'reviews.modal.textPlaceholder': 'Расскажите о вашем опыте покупки автомобиля через RB Motors...',
    'reviews.modal.cancel': 'Отмена',
    'reviews.modal.submit': 'Опубликовать',
    'reviews.modal.submitting': 'Отправка...',
    'reviews.month.0': 'января',
    'reviews.month.1': 'февраля',
    'reviews.month.2': 'марта',
    'reviews.month.3': 'апреля',
    'reviews.month.4': 'мая',
    'reviews.month.5': 'июня',
    'reviews.month.6': 'июля',
    'reviews.month.7': 'августа',
    'reviews.month.8': 'сентября',
    'reviews.month.9': 'октября',
    'reviews.month.10': 'ноября',
    'reviews.month.11': 'декабря',
    // Auth error messages
    'auth.login.emptyFields': 'Введите email и пароль',
    'auth.login.error': 'Неверный email или пароль',
    'auth.login.success': 'Вы успешно вошли в систему',
    'auth.login.errorGeneral': 'Ошибка при входе. Попробуйте позже.',
    'auth.register.emptyFields': 'Заполните все обязательные поля',
    'auth.register.passwordMismatch': 'Пароли не совпадают',
    'auth.register.passwordTooShort': 'Пароль должен содержать минимум 8 символов',
    'auth.register.error': 'Ошибка регистрации',
    'auth.register.success': 'Аккаунт создан! Добро пожаловать.',
    'auth.register.errorGeneral': 'Ошибка при регистрации. Попробуйте позже.',
    'auth.register.telegramError': 'Ошибка входа через Telegram',
    'auth.login.password': 'Пароль',
    'auth.login.passwordPlaceholder': 'Введите пароль',
    'auth.callback.loading': 'Завершение входа...',
    'auth.callback.redirect': 'Перенаправление на страницу входа...',
    'auth.callback.blocked': 'Аккаунт заблокирован.',
    'auth.callback.error': 'Ошибка входа. Попробуйте ещё раз.',
    'auth.callback.noData': 'Данные авторизации не получены.',
    // Dashboard
    'dash.title': 'Обзор',
    'dash.loading': 'Загрузка...',
    'dash.error': 'Не удалось загрузить данные',
    'dash.onboarding.title': 'Начало работы',
    'dash.onboarding.remaining': 'Выполните {n} оставшихся шагов для полного доступа',
    'dash.onboarding.goTo': 'Перейти',
    'dash.onboarding.complete.title': 'Вы готовы к торгам',
    'dash.onboarding.complete.subtitle': 'Все этапы пройдены — добро пожаловать на аукцион',
    'dash.step.register': 'Регистрация',
    'dash.step.email': 'Email подтверждён',
    'dash.step.docs': 'Документы загружены',
    'dash.step.kyc': 'KYC верификация',
    'dash.step.broker': 'Брокер назначен',
    'dash.card.balance': 'Баланс',
    'dash.card.activeBids': 'Активные ставки',
    'dash.card.favorites': 'Избранное',
    'dash.card.orders': 'Текущие заказы',
    'dash.action.catalog': 'Каталог',
    'dash.action.live': 'Live торги',
    'dash.action.documents': 'Документы',
    // Balance
    'balance.title': 'Баланс',
    'balance.loading': 'Загрузка...',
    'balance.error.balance': 'Не удалось загрузить баланс',
    'balance.error.history': 'Не удалось загрузить историю операций',
    'balance.current': 'Текущий баланс',
    'balance.verifyNotice': 'Пополнение доступно после верификации аккаунта',
    'balance.close': 'Закрыть',
    'balance.topUp': 'Пополнить',
    'balance.deposit.title': 'Пополнение баланса',
    'balance.deposit.desc': 'Выполните банковский перевод по реквизитам ниже и сообщите менеджеру. Зачисление — в течение 1–2 рабочих дней.',
    'balance.deposit.recipient': 'Получатель',
    'balance.deposit.purpose': 'Назначение платежа',
    'balance.deposit.note': 'Укажите ваш ID в назначении платежа — это необходимо для зачисления средств.',
    'balance.history.title': 'История операций',
    'balance.history.empty': 'Операций пока нет',
    'balance.history.date': 'Дата',
    'balance.history.type': 'Тип',
    'balance.history.desc': 'Описание',
    'balance.history.amount': 'Сумма',
    'balance.history.after': 'Остаток',
    'balance.type.deposit': 'Пополнение',
    'balance.type.carPayment': 'Оплата авто',
    'balance.type.commission': 'Комиссия',
    'balance.type.refund': 'Возврат',
    'balance.type.delivery': 'Доставка',
    'balance.type.customs': 'Растаможка',
    'balance.type.bidLock': 'Блокировка ставки',
    'balance.type.bidUnlock': 'Разблокировка ставки',
    'balance.type.other': 'Операция',
    // Orders
    'orders.title': 'Мои заказы',
    'orders.loading': 'Загрузка...',
    'orders.error': 'Не удалось загрузить заказы',
    'orders.empty': 'У вас пока нет заказов',
    'orders.costs': 'Стоимость',
    'orders.carPrice': 'Цена авто',
    'orders.commission': 'Комиссия',
    'orders.delivery': 'Доставка',
    'orders.customs': 'Растаможка',
    'orders.total': 'Итого',
    'orders.managerComment': 'Комментарий менеджера',
    'orders.timeline': 'История статусов',
    'orders.timeline.loading': 'Загрузка...',
    'orders.timeline.empty': 'Нет записей',
    'orders.estimate': 'Ожидаемая дата:',
    'orders.notFound': 'Лот не найден',
    'orders.status.pending': 'Ожидает подтверждения',
    'orders.status.approved': 'Подтверждён',
    'orders.status.paid': 'Оплачен',
    'orders.status.deliveredSvh': 'Доставлен на СВХ',
    'orders.status.customs': 'На растаможке',
    'orders.status.cleared': 'Растаможен',
    'orders.status.delivering': 'В доставке',
    'orders.status.completed': 'Завершён',
    // Notifications
    'notif.title': 'Уведомления',
    'notif.markAll': 'Прочитать все',
    'notif.empty': 'Уведомлений нет',
    'notif.error': 'Не удалось загрузить уведомления',
    'notif.delete': 'Удалить',
    // Watchlist
    'watchlist.title': 'Отслеживаемые',
    'watchlist.loading': 'Загрузка...',
    'watchlist.error': 'Не удалось загрузить отслеживаемые',
    'watchlist.brands': 'Отслеживаемые бренды',
    'watchlist.addBrand': 'Добавить',
    'watchlist.modal.title': 'Добавить бренд',
    'watchlist.modal.search': 'Поиск бренда...',
    'watchlist.modal.loading': 'Загрузка...',
    'watchlist.modal.empty': 'Ничего не найдено',
    'watchlist.favorites': 'Избранные лоты',
    'watchlist.lots': 'Отслеживаемые лоты',
    'watchlist.km': 'км',
    'watchlist.startPrice': 'Стартовая цена',
    'watchlist.watching': 'отслеживают',
    'watchlist.empty': 'Вы ещё не добавили лоты в отслеживаемые',
    // Calendar
    'calendar.title': 'Календарь аукционов',
    'calendar.loading': 'Загрузка...',
    'calendar.error': 'Не удалось загрузить календарь',
    'calendar.empty': 'Нет избранных лотов с запланированным аукционом',
    'calendar.browse': 'Перейти в каталог',
    'calendar.today': 'Сегодня',
    'calendar.km': 'км',
    'cal.jan': 'января', 'cal.feb': 'февраля', 'cal.mar': 'марта', 'cal.apr': 'апреля',
    'cal.may': 'мая', 'cal.jun': 'июня', 'cal.jul': 'июля', 'cal.aug': 'августа',
    'cal.sep': 'сентября', 'cal.oct': 'октября', 'cal.nov': 'ноября', 'cal.dec': 'декабря',
    'cal.sun': 'Воскресенье', 'cal.mon': 'Понедельник', 'cal.tue': 'Вторник',
    'cal.wed': 'Среда', 'cal.thu': 'Четверг', 'cal.fri': 'Пятница', 'cal.sat': 'Суббота',
    // Calculator
    'calc.title': 'Калькулятор растаможки',
    'calc.subtitle': 'Расчёт ориентировочных таможенных расходов при ввозе автомобиля в Беларусь',
    'calc.form.title': 'Параметры автомобиля',
    'calc.carPrice': 'Стоимость авто (EUR)',
    'calc.year': 'Год выпуска',
    'calc.fuelType': 'Тип топлива',
    'calc.engine': 'Объём двигателя (см³)',
    'calc.delivery': 'Доставка (EUR)',
    'calc.company': 'Комиссия компании (EUR)',
    'calc.calculate': 'Рассчитать',
    'calc.result.title': 'Итоговый расчёт',
    'calc.result.carPrice': 'Стоимость авто',
    'calc.result.customs': 'Таможенные сборы',
    'calc.result.excise': 'Акцизный сбор',
    'calc.result.duty': 'Таможенная пошлина (10%)',
    'calc.result.vat': 'НДС (20%)',
    'calc.result.pension': 'Пенсионный сбор (3%)',
    'calc.result.totalCustoms': 'Итого таможня',
    'calc.result.extra': 'Дополнительные расходы',
    'calc.result.delivery': 'Доставка',
    'calc.result.company': 'Комиссия компании',
    'calc.result.total': 'Итоговая стоимость',
    'calc.result.disclaimer': '* Расчёт является ориентировочным. Точные суммы зависят от актуального курса EUR/BYN и индивидуальных условий ввоза. Обратитесь к менеджеру для точного расчёта.',
    'calc.result.age': 'Возраст авто: {n} лет (коэфф. ×{c})',
    'calc.ph.price': 'Например: 12000',
    'calc.ph.year': 'Например: 2019',
    'calc.ph.engine': 'Например: 1600',
    'calc.ph.delivery': 'Например: 800',
    'calc.ph.company': 'Например: 500',
    'calc.error.price': 'Введите стоимость автомобиля',
    'calc.error.calc': 'Ошибка при расчёте. Попробуйте ещё раз.',
    // Traders
    'traders.title': 'Мои трейдеры',
    'traders.loading': 'Загрузка...',
    'traders.error': 'Не удалось загрузить список трейдеров',
    'traders.empty': 'У вас пока нет назначенных трейдеров',
    'traders.verified': 'Верифицирован',
    'traders.trade': 'Торговать',
    'traders.favorites': 'Избранные лоты',
    'traders.add': 'Добавить',
    'traders.fav.loading': 'Загрузка...',
    'traders.fav.empty': 'Нет избранных лотов',
    'traders.modal.search': 'Поиск по марке, модели...',
    'traders.modal.searching': 'Поиск...',
    'traders.modal.empty': 'Ничего не найдено',
    'traders.km': 'км',
    'traders.status.active': 'Активен',
    'traders.status.pending': 'Ожидает',
    'traders.status.blocked': 'Заблокирован',
    // Documents
    'docs.title': 'Документы',
    'docs.upload': 'Загрузить документ',
    'docs.loading': 'Загрузка...',
    'docs.error': 'Не удалось загрузить документы',
    'docs.required.title': 'Необходимые документы',
    'docs.action.upload': 'Загрузить',
    'docs.action.retry': 'Повторить',
    'docs.badge.pending': 'На проверке',
    'docs.badge.approved': 'Подтверждён',
    'docs.table.file': 'Файл',
    'docs.table.type': 'Тип',
    'docs.table.status': 'Статус',
    'docs.table.date': 'Дата',
    'docs.tooltip.download': 'Скачать',
    'docs.empty': 'У вас пока нет документов',
    'docs.empty.btn': 'Загрузить первый документ',
    'docs.modal.title': 'Загрузка документа',
    'docs.modal.type': 'Тип документа',
    'docs.modal.file': 'Файл',
    'docs.modal.click': 'Нажмите для выбора файла',
    'docs.modal.hint': 'PDF, JPG, PNG, DOCX — до 10 МБ',
    'docs.modal.cancel': 'Отмена',
    'docs.modal.uploading': 'Загрузка...',
    'docs.modal.submit': 'Загрузить',
    'docs.type.passport': 'Паспорт / ID',
    'docs.type.invoice': 'Инвойс',
    'docs.type.customs': 'Таможенный документ',
    'docs.type.poa': 'Доверенность',
    'docs.type.other': 'Другое',
    'docs.req.passport.label': 'Паспорт / ID',
    'docs.req.passport.desc': 'Скан или фото основного разворота',
    'docs.req.poa.label': 'Доверенность',
    'docs.req.poa.desc': 'Если действуете от лица компании',
    'docs.status.approved': 'Подтверждён',
    'docs.status.pending': 'На проверке',
    'docs.status.rejected': 'Отклонён',
    'docs.type.passportShort': 'Паспорт',
    'docs.type.customsShort': 'Таможня',
    'docs.error.fileSize': 'Максимальный размер файла — 10 МБ',
    'docs.error.upload': 'Не удалось загрузить файл. Попробуйте ещё раз.',
  },
  by: {
    // Header nav
    'nav.catalog': 'Каталог',
    'nav.auctions': 'Аўкцыёны',
    'nav.live': 'Таргі',
    'nav.schedule': 'Расклад',
    'nav.about': 'Пра нас',
    'nav.reviews': 'Водгукі',
    'nav.home': 'Галоўная',
    'header.search': 'Пошук па марцы, мадэлі...',
    'header.login': 'Увайсці',
    'header.logout': 'Выйсці',
    'header.register': 'Рэгістрацыя',
    'header.theme.dark': 'Цёмная тэма',
    'header.theme.light': 'Светлая тэма',
    'header.notifications': 'Апавяшчэнні',
    'header.favorites': 'Абраныя',
    'header.profile': 'Профіль',
    'toast.login.required': 'Увайдзіце ў акаўнт, каб убачыць абраныя',
    // Cabinet nav
    'cabinet.overview': 'Агляд',
    'cabinet.bids': 'Мае стаўкі',
    'cabinet.orders': 'Заказы',
    'cabinet.documents': 'Дакументы',
    'cabinet.balance': 'Баланс',
    'cabinet.watchlist': 'Адсочваемыя',
    'cabinet.calendar': 'Каляндар',
    'cabinet.notifications': 'Апавяшчэнні',
    'cabinet.calculator': 'Калькулятар',
    'cabinet.settings': 'Налады',
    'user.verified': 'Верыфікаваны',
    'user.notVerified': 'Не верыфікаваны',
    // About page
    'about.badge': 'Пра кампанію',
    'about.hero.title': 'RB Motors — <span class="accent-text">ваш шлях</span> да аўтамабіля з Еўропы',
    'about.hero.desc': 'Мы стварылі платформу, якая робіць куплю аўтамабіляў на еўрапейскіх аўкцыёнах простай, празрыстай і даступнай для кожнага.',
    'about.why.title': 'Чаму выбіраюць нас',
    'about.why.1.title': 'Стаўкі ў рэжыме рэальнага часу',
    'about.why.1.desc': 'Кліент заўсёды ў рэжыме рэальнага часу адсочвае стаўку па сваім аўтамабілі.',
    'about.why.2.title': 'Поўная празрыстасць здзелкі',
    'about.why.2.desc': 'Празрыстасць на кожным этапе, кантроль цэнаўтварэння, ніякіх схаваных плацяжоў.',
    'about.why.3.title': 'Суправаджэнне да дому',
    'about.why.3.desc': 'Суправаджэнне аўтамабіля да паказанага адрасу, а таксама дапамога з афармленнем усёй дакументацыі аж да пастаноўкі на ўлік.',
    'about.why.4.title': 'Экспертная праверка',
    'about.why.4.desc': 'Нашы спецыялісты правяраюць усе аўтамабілі перад пачаткам таргоў і заўсёды ўкажуць на «ката ў мяшку».',
    'about.mission.title': 'Наша місія',
    'about.mission.p1': 'Даць пакупнікам з СНД прамы доступ да еўрапейскага аўтарынку з поўным суправаджэннем — ад таргоў да дастаўкі аўтамабіля да парога.',
    'about.mission.p2': 'Мы аб\'ядноўваем тэхналогіі рэальнага часу, празрыстую аўкцыённую механіку і прафесійную лагістыку, каб кожны кліент мог набыць аўтамабіль па лепшай цане.',
    'about.values.title': 'Нашы каштоўнасці',
    'about.values.1.title': 'Празрыстасць',
    'about.values.1.desc': 'Адкрытыя таргі, сумленныя цэны, поўная гісторыя кожнага аўтамабіля',
    'about.values.2.title': 'Хуткасць',
    'about.values.2.desc': 'Таргі ў рэжыме рэальнага часу, аператыўная дастаўка, хуткае расцамажванне',
    'about.values.3.title': 'Надзейнасць',
    'about.values.3.desc': 'Правераныя аўтамабілі, гарантаваная дастаўка, юрыдычная чысціня',
    'about.team.title': 'Каманда',
    // Footer
    'footer.desc': 'Платформа онлайн-аўкцыёну аўтамабіляў з Еўропы. Празрыстыя таргі ў рэжыме рэальнага часу.',
    'footer.col.auctions': 'Аўкцыёны',
    'footer.catalog': 'Каталог лотаў',
    'footer.live': 'Live таргі',
    'footer.ending': 'Якія завяршаюцца хутка',
    'footer.liveTrading': 'Live Trading',
    'footer.calendar': 'Каляндар аўкцыёнаў',
    'footer.col.buyers': 'Пакупнікам',
    'footer.how.register': 'Як зарэгістравацца',
    'footer.how.bids': 'Як рабіць стаўкі',
    'footer.payment': 'Аплата і дастаўка',
    'footer.customs': 'Расцамажванне аўто',
    'footer.guarantee': 'Гарантыі і вяртанне',
    'footer.col.company': 'Кампанія',
    'footer.about': 'Пра нас',
    'footer.faq': 'FAQ',
    'footer.contacts': 'Кантакты',
    'footer.jobs': 'Вакансіі',
    'footer.blog': 'Блог',
    'footer.partners': 'Партнёры:',
    'footer.copyright': '© 2025–2026 RB Motors. Усе правы абаронены.',
    'footer.privacy': 'Палітыка канфідэнцыяльнасці',
    'footer.terms': 'Умовы выкарыстання',
    'footer.cookies': 'Файлы cookie',
    // Settings
    'settings.title': 'Налады',
    'settings.profile': 'Профіль',
    'settings.loading': 'Загрузка профілю...',
    'settings.firstName': 'Імя',
    'settings.lastName': 'Прозвішча',
    'settings.phone': 'Тэлефон',
    'settings.saveProfile': 'Захаваць профіль',
    'settings.regional': 'Рэгіянальныя налады',
    'settings.country': 'Краіна',
    'settings.language': 'Мова',
    'settings.currency': 'Валюта',
    'settings.saveRegional': 'Захаваць рэгіянальныя налады',
    'settings.restricted.title': 'Абмежаваны рэгіён',
    'settings.restricted.desc': 'Па патрабаванні партнёра rbmotors.de, для карыстальнікаў з Расіі і Рэспублікі Беларусь функцыянал платформы, уключаючы папаўненне балансу, можа быць абмежаваны.',
    'settings.saved.profile': 'Профіль захаваны',
    'settings.saved.regional': 'Рэгіянальныя налады захаваны',
    'settings.error.profile': 'Памылка захавання профілю',
    'settings.error.regional': 'Памылка захавання',
    // Auth
    'auth.login.title': 'Уваход у RB Motors',
    'auth.login.subtitle': 'Увайдзіце, каб удзельнічаць у таргах',
    'auth.login.forgot': 'Забылі пароль?',
    'auth.login.submit': 'Увайсці',
    'auth.login.noAccount': 'Няма акаўнту?',
    'auth.login.register': 'Зарэгістравацца',
    'auth.register.title': 'Рэгістрацыя ў RB Motors',
    'auth.register.subtitle': 'Стварыце акаўнт для ўдзелу ў таргах',
    'auth.register.firstName': 'Імя',
    'auth.register.lastName': 'Прозвішча',
    'auth.register.phone': 'Тэлефон',
    'auth.register.password': 'Пароль',
    'auth.register.confirm': 'Пацвердзіце пароль',
    'auth.register.submit': 'Зарэгістравацца',
    'auth.register.hasAccount': 'Ужо ёсць акаўнт?',
    'auth.register.login': 'Увайсці',
    // Live trading page
    'live.noAuctions': 'Зараз таргоў няма',
    'live.loadingSchedule': 'Загрузка раскладу...',
    'live.nextAuction': 'Наступны аўкцыён —',
    'live.noSchedule': 'Расклад пакуль не аб\'яўлены',
    'live.viewSchedule': 'Глядзець расклад',
    'live.tradingFor': 'Таргуюся за:',
    'live.selectTrader': 'Выберыце трэйдара',
    'live.today': 'Сёння ў',
    'live.tomorrow': 'Заўтра ў',
    'time.at': 'ў',
    // Auctions schedule page
    'auctions.title': 'Расклад аўкцыёнаў',
    'auctions.subtitle': 'Выберыце дзень, каб убачыць лоты',
    'auctions.live': 'Ідзе',
    'auctions.joinBid': 'У таргі',
    'auctions.lot1': 'лот',
    'auctions.lot2': 'лоты',
    'auctions.lots': 'лотаў',
    'auctions.km': 'км',
    // Shared fuel types
    'fuel.petrol': 'Бензін',
    'fuel.diesel': 'Дызель',
    'fuel.hybrid': 'Гібрыд',
    'fuel.electric': 'Электра',
    'fuel.lpg': 'Газ',
    'fuel.other': 'Іншае',
    // Shared transmissions
    'trans.automatic': 'Аўтамат',
    'trans.manual': 'Механіка',
    // Home page
    'home.hero.title': 'Знайдзіце аўтамабіль мары',
    'home.hero.subtitle': 'Аўтамабілі з еўрапейскіх аўкцыёнаў BCA Europe',
    'home.hero.subtitleCount': 'Больш за {n} аўтамабіляў з еўрапейскіх аўкцыёнаў',
    'home.hero.browse': 'Глядзець каталог',
    'home.popular': 'Папулярнае:',
    'home.auctions.title': 'Аўтамабілі на аўкцыёне',
    'home.auctions.count': '{n} аўтамабіляў у каталогу',
    'home.brands': 'Папулярныя маркі',
    'home.startingPrice': 'Стартавая цана',
    'home.km': 'км',
    'home.seeAll': 'Глядзець усе аўтамабілі',
    'home.recent': 'Нядаўна дабаўленыя',
    'home.recentSub': 'Новыя лоты з BCA Europe',
    'home.seeAllCars': 'Усе аўтамабілі',
    'home.details': 'Падрабязней',
    'home.loading': 'Загрузка...',
    'home.noLots': 'Пакуль няма лотаў у базе.',
    'home.cta.title': 'Гатовы купіць аўта з еўрапейскага аўкцыёну?',
    'home.cta.desc': 'Зарэгіструйцеся, папоўніце баланс і пачніце гандляваць ужо сёння. Мы возьмем дастаўку і расцамажванне.',
    'home.cta.create': 'Стварыць акаўнт',
    'home.cta.browse': 'Глядзець каталог',
    'home.cta.verified': 'Правераныя аўта',
    'home.cta.guarantee': 'Гарантыя здзелкі',
    'home.cta.delivery': 'Дастаўка пад ключ',
    'home.how': 'Як гэта працуе',
    'home.step1.title': 'Рэгістрацыя',
    'home.step1.desc': 'Стварыце акаўнт і прайдзіце верыфікацыю',
    'home.step2.title': 'Папоўніце баланс',
    'home.step2.desc': 'Унясіце дэпазіт для ўдзелу ў таргах',
    'home.step3.title': 'Выберыце аўта',
    'home.step3.desc': 'Знайдзіце аўтамабіль у каталогу або на live-таргах',
    'home.step4.title': 'Зрабіце стаўку',
    'home.step4.desc': 'Удзельнічайце ў аўкцыёне ў рэжыме рэальнага часу',
    'home.step5.title': 'Аплаціце лот',
    'home.step5.desc': 'Пасля перамогі аплаціце аўтамабіль',
    'home.step6.title': 'Дастаўка і расцамажванне',
    'home.step6.desc': 'Мы дасціпна і расцамажым аўта для вас',
    'home.step7.title': 'Атрымайце аўта',
    'home.step7.desc': 'Забярыце аўтамабіль па вашым адрасе',
    // Catalog page
    'catalog.title': 'Каталог аўтамабіляў',
    'catalog.lots': 'лотаў',
    'catalog.filters': 'Фільтры',
    'catalog.reset': 'Скінуць',
    'catalog.brand': 'Марка',
    'catalog.allBrands': 'Усе маркі',
    'catalog.model': 'Мадэль',
    'catalog.modelPlaceholder': 'Пачніце ўводзіць мадэль...',
    'catalog.year': 'Год выпуску',
    'catalog.price': 'Цана, EUR',
    'catalog.fuel': 'Паліва',
    'catalog.allFuels': 'Усе',
    'catalog.trans': 'Скрыня перадач',
    'catalog.mileage': 'Пробег, км',
    'catalog.engine': 'Аб\'ём рухавіка, см³',
    'catalog.find': 'Знайсці',
    'catalog.loading': 'Загрузка...',
    'catalog.notFound': 'Лоты не знойдзены. Паспрабуйце змяніць фільтры.',
    'catalog.km': 'км',
    'catalog.ps': 'л.с.',
    'catalog.currentBid': 'Бягучая стаўка',
    'catalog.startingPrice': 'Стартавая цана',
    'catalog.loadingMore': 'Загрузка...',
    'catalog.allLoaded': 'Усе лоты загружаны',
    'catalog.from': 'Ад',
    'catalog.to': 'Да',
    'sort.new': 'Новыя',
    'sort.upcoming': 'Бліжэйшыя аўкцыёны',
    'sort.priceAsc': 'Цана ↑',
    'sort.priceDesc': 'Цана ↓',
    'sort.yearDesc': 'Год ↓',
    'sort.mileageAsc': 'Пробег ↑',
    // Lot detail spec labels
    'spec.power': 'Магутнасць',
    'spec.fuel': 'Паліва',
    'spec.mileage': 'Пробег',
    'spec.year': 'Год',
    'spec.transmission': 'КПП',
    'spec.color': 'Колер',
    'spec.type': 'Тып',
    'spec.doors': 'Дзверы',
    'spec.seats': 'Месцы',
    'spec.gears': 'Перадачы',
    'spec.volume': 'Аб\'ём',
    'spec.emission': 'Эмісія',
    'spec.owners': 'Уладальнікаў',
    'spec.keys': 'Ключоў',
    'spec.ps': 'л.с.',
    'spec.kw': 'кВт',
    'spec.km': 'км',
    // Lot detail page
    'lot.loading': 'Загрузка...',
    'lot.notFound': 'Лот не знойдзены',
    'lot.backToCatalog': 'Вярнуцца ў каталог',
    'lot.home': 'Галоўная',
    'lot.catalog': 'Каталог',
    'lot.noPhoto': 'Няма фота',
    'lot.gallery.all': 'Усе фота',
    'lot.gallery.exterior': 'Экстэр\'ер',
    'lot.gallery.interior': 'Інтэр\'ер',
    'lot.gallery.damage': 'Пашкоджанні',
    'lot.specs': 'Характарыстыкі',
    'lot.pending': 'Лот агледжваецца экспертамі, інфармацыя з\'явіцца пазней',
    'lot.equipment': 'Камплектацыя',
    'lot.showAll': 'Паказаць усё ({n})',
    'lot.showLess': 'Схаваць',
    'lot.serviceHistory': 'Гісторыя абслугоўвання',
    'lot.historyDate': 'Дата',
    'lot.historyMileage': 'Пробег',
    'lot.historyDesc': 'Апісанне',
    'lot.historyCompany': 'Кампанія',
    'lot.accident': 'Аварыя / Пашкоджанні',
    'lot.damagePhotos': 'Фота пашкоджанняў',
    'lot.body': 'Кузаў',
    'lot.interior': 'Салон',
    'lot.tires': 'Шыны / Колавыя дыскі',
    'lot.tiresPosition': 'Пазіцыя',
    'lot.tiresDepth': 'Глыбіня пратэктара',
    'lot.tiresSize': 'Памер',
    'lot.stoneChips': 'Сколы / Ветравое шкло',
    'lot.seats': 'Сядзенні',
    'lot.general': 'Агульная інфармацыя',
    'lot.parking': 'Стаянка',
    'lot.condition': 'Стан',
    'lot.startingPrice': 'Стартавая цана',
    'lot.pricePending': 'Чакаецца',
    'lot.buyNow': 'Цана выкупу',
    'lot.currentBid': 'Бягучая стаўка',
    'lot.watching': 'назіраюць',
    'lot.ended': 'Таргі завершаны',
    'lot.winning': 'Вы лідзіруеце!',
    'lot.outbid': 'Ваша стаўка перабітая',
    'lot.autobidActive': 'Аўта-стаўка да {n} {cur}',
    'lot.bidSuccess': 'Стаўка прынята!',
    'lot.processing': 'Апрацоўка...',
    'lot.makeBid': 'Зрабіць стаўку',
    'lot.bidFor': 'Стаўка за {name}',
    'lot.autoBidLabel': 'Аўта-стаўка (Pre-bid)',
    'lot.autoBidHint': 'Сістэма аўтаматычна перабівае канкурэнтаў да ўказанага ліміту.',
    'lot.autoBidPlaceholder': 'Ліміт ад {n}',
    'lot.autoBidSet': 'Усталяваць',
    'lot.minPayment': 'Мінімальны плацёж',
    'lot.origin': 'Вытворчасць:',
    'lot.seller': 'Прадавец:',
    'lot.inFavorite': 'У абраных',
    'lot.addFavorite': 'У абраныя',
    'lot.tradingFor': 'Таргуюся за:',
    'lot.selectTrader': '— Выберыце кліента —',
    'lot.loginPrompt': 'каб зрабіць стаўку',
    'lot.loginLink': 'Увайдзіце',
    'lot.bidHistory': 'Апошнія стаўкі',
    'lot.autoBidTooltip': 'Аўта-стаўка',
    'lot.brokerNotice': 'Таргі вядзе ваш брокер. Дадайце лот у абраныя — брокер зробіць стаўку.',
    'lot.minBidError': 'Мінімальная стаўка: €{n}',
    'lot.noResponse': 'Няма адказу ад сервера. Паспрабуйце яшчэ раз.',
    'lot.minAutoBidError': 'Аўта-стаўка павінна быць не меней €{n}',
    // Contacts page
    'contacts.badge': 'Кантакты',
    'contacts.title': 'Звяжыцеся з намі',
    'contacts.subtitle': 'Мы заўсёды на сувязі і гатовы дапамагчы',
    'contacts.phone': 'Тэлефон',
    'contacts.hours': 'Час працы',
    'contacts.hoursValue': 'Пн — Пт: 9:00 — 18:00',
    'contacts.formTitle': 'Напішыце нам',
    'contacts.name': 'Імя',
    'contacts.namePlaceholder': 'Ваша імя',
    'contacts.messageLabel': 'Паведамленне',
    'contacts.messagePlaceholder': 'Ваша паведамленне...',
    'contacts.submit': 'Адправіць',
    // Reviews page
    'reviews.badge': 'Водгукі кліентаў',
    'reviews.title': 'Што кажуць <span class="accent-text">нашы кліенты</span>',
    'reviews.subtitle': 'Сапраўдныя водгукі пакупнікоў, якія набылі аўтамабілі праз нашу платформу. Мы цэнім кожную думку.',
    'reviews.promo.title': 'Акцыя: відэа-водгук = 100 USDT',
    'reviews.promo.text': 'Запішы відэа-водгук са сваім аўта, купленым праз RB Motors, у красавіку 2026 і атрымай кэшбэк <strong>100 USDT</strong> на баланс.',
    'reviews.promo.countdownLabel': 'Да старту акцыі:',
    'reviews.promo.days': 'дн',
    'reviews.promo.hours': 'г',
    'reviews.promo.minutes': 'хв',
    'reviews.promo.seconds': 'с',
    'reviews.promo.btn': 'Падрабязней',
    'reviews.loading': 'Загрузка водгукаў...',
    'reviews.totalCount': '{n} водгукаў',
    'reviews.leaveReview': 'Пакінуць водгук',
    'reviews.loginToReview': 'Увайдзіце, каб пакінуць водгук',
    'reviews.loadMore': 'Паказаць яшчэ',
    'reviews.loadingMore': 'Загрузка...',
    'reviews.noReviews': 'Водгукаў пакуль няма. Будзьце першым!',
    'reviews.error.load': 'Не атрымалася загрузіць водгукі',
    'reviews.modal.title': 'Пакінуць водгук',
    'reviews.modal.success.title': 'Дзякуй за водгук!',
    'reviews.modal.success.text': 'Ваш водгук паспяхова апублікаваны.',
    'reviews.modal.ratingLabel': 'Ваша адзнака',
    'reviews.modal.nameLabel': 'Ваша імя',
    'reviews.modal.namePlaceholder': 'Як вас падпісаць? (неабавязкова)',
    'reviews.modal.textLabel': 'Ваш водгук',
    'reviews.modal.textPlaceholder': 'Раскажыце пра ваш досвед пакупкі аўтамабіля праз RB Motors...',
    'reviews.modal.cancel': 'Адмена',
    'reviews.modal.submit': 'Апублікаваць',
    'reviews.modal.submitting': 'Адпраўка...',
    'reviews.month.0': 'студзеня',
    'reviews.month.1': 'лютага',
    'reviews.month.2': 'сакавіка',
    'reviews.month.3': 'красавіка',
    'reviews.month.4': 'мая',
    'reviews.month.5': 'чэрвеня',
    'reviews.month.6': 'ліпеня',
    'reviews.month.7': 'жніўня',
    'reviews.month.8': 'верасня',
    'reviews.month.9': 'кастрычніка',
    'reviews.month.10': 'лістапада',
    'reviews.month.11': 'снежня',
    // Auth error messages
    'auth.login.emptyFields': 'Увядзіце email і пароль',
    'auth.login.error': 'Няправільны email або пароль',
    'auth.login.success': 'Вы паспяхова ўвайшлі ў сістэму',
    'auth.login.errorGeneral': 'Памылка пры ўваходзе. Паспрабуйце пазней.',
    'auth.register.emptyFields': 'Запоўніце ўсе абавязковыя палі',
    'auth.register.passwordMismatch': 'Паролі не супадаюць',
    'auth.register.passwordTooShort': 'Пароль павінен змяшчаць мінімум 8 сімвалаў',
    'auth.register.error': 'Памылка рэгістрацыі',
    'auth.register.success': 'Акаўнт створаны! Сардэчна запрашаем.',
    'auth.register.errorGeneral': 'Памылка пры рэгістрацыі. Паспрабуйце пазней.',
    'auth.register.telegramError': 'Памылка ўваходу праз Telegram',
    'auth.login.password': 'Пароль',
    'auth.login.passwordPlaceholder': 'Увядзіце пароль',
    'auth.callback.loading': 'Завяршэнне ўваходу...',
    'auth.callback.redirect': 'Перанакіраванне на старонку ўваходу...',
    'auth.callback.blocked': 'Акаўнт заблакаваны.',
    'auth.callback.error': 'Памылка ўваходу. Паспрабуйце яшчэ раз.',
    'auth.callback.noData': 'Дадзеныя аўтарызацыі не атрыманы.',
    // Dashboard
    'dash.title': 'Агляд',
    'dash.loading': 'Загрузка...',
    'dash.error': 'Не ўдалося загрузіць дадзеныя',
    'dash.onboarding.title': 'Пачатак работы',
    'dash.onboarding.remaining': 'Выканайце {n} астатніх крокаў для поўнага доступу',
    'dash.onboarding.goTo': 'Перайсці',
    'dash.onboarding.complete.title': 'Вы гатовы да таргоў',
    'dash.onboarding.complete.subtitle': 'Усе этапы пройдзены — сардэчна запрашаем на аўкцыён',
    'dash.step.register': 'Рэгістрацыя',
    'dash.step.email': 'Email пацверджаны',
    'dash.step.docs': 'Дакументы загружаны',
    'dash.step.kyc': 'KYC верыфікацыя',
    'dash.step.broker': 'Брокер прызначаны',
    'dash.card.balance': 'Баланс',
    'dash.card.activeBids': 'Актыўныя стаўкі',
    'dash.card.favorites': 'Абраныя',
    'dash.card.orders': 'Бягучыя заказы',
    'dash.action.catalog': 'Каталог',
    'dash.action.live': 'Live таргі',
    'dash.action.documents': 'Дакументы',
    // Balance
    'balance.title': 'Баланс',
    'balance.loading': 'Загрузка...',
    'balance.error.balance': 'Не ўдалося загрузіць баланс',
    'balance.error.history': 'Не ўдалося загрузіць гісторыю аперацый',
    'balance.current': 'Бягучы баланс',
    'balance.verifyNotice': 'Папаўненне даступна пасля верыфікацыі акаўнту',
    'balance.close': 'Закрыць',
    'balance.topUp': 'Папоўніць',
    'balance.deposit.title': 'Папаўненне балансу',
    'balance.deposit.desc': 'Выканайце банкаўскі пераклад па рэквізітах ніжэй і паведаміце менеджэру. Залічэнне — на працягу 1–2 працоўных дзён.',
    'balance.deposit.recipient': 'Атрымальнік',
    'balance.deposit.purpose': 'Прызначэнне плацяжу',
    'balance.deposit.note': 'Укажыце ваш ID ў прызначэнні плацяжу — гэта неабходна для залічэння сродкаў.',
    'balance.history.title': 'Гісторыя аперацый',
    'balance.history.empty': 'Аперацый пакуль няма',
    'balance.history.date': 'Дата',
    'balance.history.type': 'Тып',
    'balance.history.desc': 'Апісанне',
    'balance.history.amount': 'Сума',
    'balance.history.after': 'Астатак',
    'balance.type.deposit': 'Папаўненне',
    'balance.type.carPayment': 'Аплата аўта',
    'balance.type.commission': 'Камісія',
    'balance.type.refund': 'Вяртанне',
    'balance.type.delivery': 'Дастаўка',
    'balance.type.customs': 'Расцамажванне',
    'balance.type.bidLock': 'Блакіроўка стаўкі',
    'balance.type.bidUnlock': 'Разблакіроўка стаўкі',
    'balance.type.other': 'Аперацыя',
    // Orders
    'orders.title': 'Мае заказы',
    'orders.loading': 'Загрузка...',
    'orders.error': 'Не ўдалося загрузіць заказы',
    'orders.empty': 'У вас пакуль няма заказаў',
    'orders.costs': 'Кошт',
    'orders.carPrice': 'Цана аўта',
    'orders.commission': 'Камісія',
    'orders.delivery': 'Дастаўка',
    'orders.customs': 'Расцамажванне',
    'orders.total': 'Усяго',
    'orders.managerComment': 'Каментарый менеджэра',
    'orders.timeline': 'Гісторыя статусаў',
    'orders.timeline.loading': 'Загрузка...',
    'orders.timeline.empty': 'Няма запісаў',
    'orders.estimate': 'Чаканая дата:',
    'orders.notFound': 'Лот не знойдзены',
    'orders.status.pending': 'Чакае пацверджання',
    'orders.status.approved': 'Пацверджаны',
    'orders.status.paid': 'Аплачаны',
    'orders.status.deliveredSvh': 'Дастаўлены на СВХ',
    'orders.status.customs': 'На расцамажванні',
    'orders.status.cleared': 'Расцамажаны',
    'orders.status.delivering': 'У дастаўцы',
    'orders.status.completed': 'Завершаны',
    // Notifications
    'notif.title': 'Апавяшчэнні',
    'notif.markAll': 'Прачытаць усе',
    'notif.empty': 'Апавяшчэнняў няма',
    'notif.error': 'Не ўдалося загрузіць апавяшчэнні',
    'notif.delete': 'Выдаліць',
    // Watchlist
    'watchlist.title': 'Адсочваемыя',
    'watchlist.loading': 'Загрузка...',
    'watchlist.error': 'Не ўдалося загрузіць адсочваемыя',
    'watchlist.brands': 'Адсочваемыя брэнды',
    'watchlist.addBrand': 'Дадаць',
    'watchlist.modal.title': 'Дадаць брэнд',
    'watchlist.modal.search': 'Пошук брэнда...',
    'watchlist.modal.loading': 'Загрузка...',
    'watchlist.modal.empty': 'Нічога не знойдзена',
    'watchlist.favorites': 'Абраныя лоты',
    'watchlist.lots': 'Адсочваемыя лоты',
    'watchlist.km': 'км',
    'watchlist.startPrice': 'Стартавая цана',
    'watchlist.watching': 'адсочваюць',
    'watchlist.empty': 'Вы яшчэ не дадалі лоты ў адсочваемыя',
    // Calendar
    'calendar.title': 'Каляндар аўкцыёнаў',
    'calendar.loading': 'Загрузка...',
    'calendar.error': 'Не ўдалося загрузіць каляндар',
    'calendar.empty': 'Няма абраных лотаў з запланаваным аўкцыёнам',
    'calendar.browse': 'Перайсці ў каталог',
    'calendar.today': 'Сёння',
    'calendar.km': 'км',
    'cal.jan': 'студзеня', 'cal.feb': 'лютага', 'cal.mar': 'сакавіка', 'cal.apr': 'красавіка',
    'cal.may': 'мая', 'cal.jun': 'чэрвеня', 'cal.jul': 'ліпеня', 'cal.aug': 'жніўня',
    'cal.sep': 'верасня', 'cal.oct': 'кастрычніка', 'cal.nov': 'лістапада', 'cal.dec': 'снежня',
    'cal.sun': 'Нядзеля', 'cal.mon': 'Панядзелак', 'cal.tue': 'Аўторак',
    'cal.wed': 'Серада', 'cal.thu': 'Чацвер', 'cal.fri': 'Пятніца', 'cal.sat': 'Субота',
    // Calculator
    'calc.title': 'Калькулятар расцамажвання',
    'calc.subtitle': 'Разлік арыентыровачных мытных выдаткаў пры ўвозе аўтамабіля ў Беларусь',
    'calc.form.title': 'Параметры аўтамабіля',
    'calc.carPrice': 'Кошт аўта (EUR)',
    'calc.year': 'Год выпуску',
    'calc.fuelType': 'Тып паліва',
    'calc.engine': 'Аб\'ём рухавіка (см³)',
    'calc.delivery': 'Дастаўка (EUR)',
    'calc.company': 'Камісія кампаніі (EUR)',
    'calc.calculate': 'Разлічыць',
    'calc.result.title': 'Выніковы разлік',
    'calc.result.carPrice': 'Кошт аўта',
    'calc.result.customs': 'Мытныя зборы',
    'calc.result.excise': 'Акцызны збор',
    'calc.result.duty': 'Мытная пошліна (10%)',
    'calc.result.vat': 'ПДВ (20%)',
    'calc.result.pension': 'Пенсійны збор (3%)',
    'calc.result.totalCustoms': 'Усяго мытня',
    'calc.result.extra': 'Дадатковыя выдаткі',
    'calc.result.delivery': 'Дастаўка',
    'calc.result.company': 'Камісія кампаніі',
    'calc.result.total': 'Выніковы кошт',
    'calc.result.disclaimer': '* Разлік з\'яўляецца арыентыровачным. Дакладныя сумы залежаць ад актуальнага курсу EUR/BYN і індывідуальных умоў увозу. Звярніцеся да менеджэра для дакладнага разліку.',
    'calc.result.age': 'Узрост аўта: {n} гадоў (каэф. ×{c})',
    'calc.ph.price': 'Напрыклад: 12000',
    'calc.ph.year': 'Напрыклад: 2019',
    'calc.ph.engine': 'Напрыклад: 1600',
    'calc.ph.delivery': 'Напрыклад: 800',
    'calc.ph.company': 'Напрыклад: 500',
    'calc.error.price': 'Увядзіце кошт аўтамабіля',
    'calc.error.calc': 'Памылка пры разліку. Паспрабуйце яшчэ раз.',
    // Traders
    'traders.title': 'Мае трэйдары',
    'traders.loading': 'Загрузка...',
    'traders.error': 'Не ўдалося загрузіць спіс трэйдараў',
    'traders.empty': 'У вас пакуль няма прызначаных трэйдараў',
    'traders.verified': 'Верыфікаваны',
    'traders.trade': 'Гандляваць',
    'traders.favorites': 'Абраныя лоты',
    'traders.add': 'Дадаць',
    'traders.fav.loading': 'Загрузка...',
    'traders.fav.empty': 'Няма абраных лотаў',
    'traders.modal.search': 'Пошук па марцы, мадэлі...',
    'traders.modal.searching': 'Пошук...',
    'traders.modal.empty': 'Нічога не знойдзена',
    'traders.km': 'км',
    'traders.status.active': 'Актыўны',
    'traders.status.pending': 'Чакае',
    'traders.status.blocked': 'Заблакаваны',
    // Documents
    'docs.title': 'Дакументы',
    'docs.upload': 'Загрузіць дакумент',
    'docs.loading': 'Загрузка...',
    'docs.error': 'Не ўдалося загрузіць дакументы',
    'docs.required.title': 'Неабходныя дакументы',
    'docs.action.upload': 'Загрузіць',
    'docs.action.retry': 'Паўтарыць',
    'docs.badge.pending': 'На праверцы',
    'docs.badge.approved': 'Пацверджаны',
    'docs.table.file': 'Файл',
    'docs.table.type': 'Тып',
    'docs.table.status': 'Статус',
    'docs.table.date': 'Дата',
    'docs.tooltip.download': 'Спампаваць',
    'docs.empty': 'У вас пакуль няма дакументаў',
    'docs.empty.btn': 'Загрузіць першы дакумент',
    'docs.modal.title': 'Загрузка дакумента',
    'docs.modal.type': 'Тып дакумента',
    'docs.modal.file': 'Файл',
    'docs.modal.click': 'Націсніце для выбару файла',
    'docs.modal.hint': 'PDF, JPG, PNG, DOCX — да 10 МБ',
    'docs.modal.cancel': 'Адмена',
    'docs.modal.uploading': 'Загрузка...',
    'docs.modal.submit': 'Загрузіць',
    'docs.type.passport': 'Пашпарт / ID',
    'docs.type.invoice': 'Інвойс',
    'docs.type.customs': 'Мытны дакумент',
    'docs.type.poa': 'Даверанасць',
    'docs.type.other': 'Іншае',
    'docs.req.passport.label': 'Пашпарт / ID',
    'docs.req.passport.desc': 'Скан або фота асноўнага разваротку',
    'docs.req.poa.label': 'Даверанасць',
    'docs.req.poa.desc': 'Калі дзейнічаеце ад імя кампаніі',
    'docs.status.approved': 'Пацверджаны',
    'docs.status.pending': 'На праверцы',
    'docs.status.rejected': 'Адхілены',
    'docs.type.passportShort': 'Пашпарт',
    'docs.type.customsShort': 'Мытня',
    'docs.error.fileSize': 'Максімальны памер файла — 10 МБ',
    'docs.error.upload': 'Не ўдалося загрузіць файл. Паспрабуйце яшчэ раз.',
  },
  en: {
    // Header nav
    'nav.catalog': 'Catalog',
    'nav.auctions': 'Auctions',
    'nav.live': 'Live Bids',
    'nav.schedule': 'Schedule',
    'nav.about': 'About',
    'nav.reviews': 'Reviews',
    'nav.home': 'Home',
    'header.search': 'Search by make, model...',
    'header.login': 'Log in',
    'header.logout': 'Log out',
    'header.register': 'Register',
    'header.theme.dark': 'Dark mode',
    'header.theme.light': 'Light mode',
    'header.notifications': 'Notifications',
    'header.favorites': 'Favourites',
    'header.profile': 'Profile',
    'toast.login.required': 'Log in to see your favourites',
    // Cabinet nav
    'cabinet.overview': 'Overview',
    'cabinet.bids': 'My Bids',
    'cabinet.orders': 'Orders',
    'cabinet.documents': 'Documents',
    'cabinet.balance': 'Balance',
    'cabinet.watchlist': 'Watchlist',
    'cabinet.calendar': 'Calendar',
    'cabinet.notifications': 'Notifications',
    'cabinet.calculator': 'Calculator',
    'cabinet.settings': 'Settings',
    'user.verified': 'Verified',
    'user.notVerified': 'Not Verified',
    // About page
    'about.badge': 'About Us',
    'about.hero.title': 'RB Motors — <span class="accent-text">your gateway</span> to European cars',
    'about.hero.desc': 'We built a platform that makes buying cars at European auctions simple, transparent, and accessible to everyone.',
    'about.why.title': 'Why choose us',
    'about.why.1.title': 'Real-time bidding',
    'about.why.1.desc': 'Clients always track their bid on a vehicle in real time.',
    'about.why.2.title': 'Full transaction transparency',
    'about.why.2.desc': 'Transparency at every step, controlled pricing, no hidden fees.',
    'about.why.3.title': 'Delivery to your door',
    'about.why.3.desc': 'We accompany the vehicle to the specified address and assist with all paperwork, including vehicle registration.',
    'about.why.4.title': 'Expert inspection',
    'about.why.4.desc': 'Our specialists inspect every vehicle before bidding begins and will always flag any hidden issues.',
    'about.mission.title': 'Our Mission',
    'about.mission.p1': 'To give CIS buyers direct access to the European car market with full support — from bidding to doorstep delivery.',
    'about.mission.p2': 'We combine real-time technology, transparent auction mechanics, and professional logistics so every client can buy a car at the best price.',
    'about.values.title': 'Our Values',
    'about.values.1.title': 'Transparency',
    'about.values.1.desc': 'Open auctions, fair prices, complete history of every vehicle',
    'about.values.2.title': 'Speed',
    'about.values.2.desc': 'Real-time bidding, fast delivery, swift customs clearance',
    'about.values.3.title': 'Reliability',
    'about.values.3.desc': 'Verified vehicles, guaranteed delivery, legal clarity',
    'about.team.title': 'Team',
    // Footer
    'footer.desc': 'Online car auction platform from Europe. Transparent real-time bidding.',
    'footer.col.auctions': 'Auctions',
    'footer.catalog': 'Lot Catalog',
    'footer.live': 'Live Bidding',
    'footer.ending': 'Ending Soon',
    'footer.liveTrading': 'Live Trading',
    'footer.calendar': 'Auction Calendar',
    'footer.col.buyers': 'For Buyers',
    'footer.how.register': 'How to Register',
    'footer.how.bids': 'How to Bid',
    'footer.payment': 'Payment & Delivery',
    'footer.customs': 'Car Customs Clearance',
    'footer.guarantee': 'Guarantees & Returns',
    'footer.col.company': 'Company',
    'footer.about': 'About Us',
    'footer.faq': 'FAQ',
    'footer.contacts': 'Contacts',
    'footer.jobs': 'Careers',
    'footer.blog': 'Blog',
    'footer.partners': 'Partners:',
    'footer.copyright': '© 2025–2026 RB Motors. All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Use',
    'footer.cookies': 'Cookies',
    // Settings
    'settings.title': 'Settings',
    'settings.profile': 'Profile',
    'settings.loading': 'Loading profile...',
    'settings.firstName': 'First Name',
    'settings.lastName': 'Last Name',
    'settings.phone': 'Phone',
    'settings.saveProfile': 'Save Profile',
    'settings.regional': 'Regional Settings',
    'settings.country': 'Country',
    'settings.language': 'Language',
    'settings.currency': 'Currency',
    'settings.saveRegional': 'Save Regional Settings',
    'settings.restricted.title': 'Restricted Region',
    'settings.restricted.desc': 'At the request of our partner rbmotors.de, certain platform features, including balance top-up, may be restricted for users from Russia and the Republic of Belarus.',
    'settings.saved.profile': 'Profile saved',
    'settings.saved.regional': 'Regional settings saved',
    'settings.error.profile': 'Error saving profile',
    'settings.error.regional': 'Error saving settings',
    // Auth
    'auth.login.title': 'Log in to RB Motors',
    'auth.login.subtitle': 'Log in to start bidding',
    'auth.login.forgot': 'Forgot password?',
    'auth.login.submit': 'Log In',
    'auth.login.noAccount': 'No account?',
    'auth.login.register': 'Register',
    'auth.register.title': 'Create an RB Motors account',
    'auth.register.subtitle': 'Create an account to participate in auctions',
    'auth.register.firstName': 'First Name',
    'auth.register.lastName': 'Last Name',
    'auth.register.phone': 'Phone',
    'auth.register.password': 'Password',
    'auth.register.confirm': 'Confirm Password',
    'auth.register.submit': 'Register',
    'auth.register.hasAccount': 'Already have an account?',
    'auth.register.login': 'Log In',
    // Live trading page
    'live.noAuctions': 'No active auctions',
    'live.loadingSchedule': 'Loading schedule...',
    'live.nextAuction': 'Next auction —',
    'live.noSchedule': 'No schedule announced yet',
    'live.viewSchedule': 'View schedule',
    'live.tradingFor': 'Bidding for:',
    'live.selectTrader': 'Select trader',
    'live.today': 'Today at',
    'live.tomorrow': 'Tomorrow at',
    'time.at': 'at',
    // Auctions schedule page
    'auctions.title': 'Auction Schedule',
    'auctions.subtitle': 'Select a day to view lots',
    'auctions.live': 'Live',
    'auctions.joinBid': 'Join Bid',
    'auctions.lot1': 'lot',
    'auctions.lot2': 'lots',
    'auctions.lots': 'lots',
    'auctions.km': 'km',
    // Shared fuel types
    'fuel.petrol': 'Petrol',
    'fuel.diesel': 'Diesel',
    'fuel.hybrid': 'Hybrid',
    'fuel.electric': 'Electric',
    'fuel.lpg': 'LPG',
    'fuel.other': 'Other',
    // Shared transmissions
    'trans.automatic': 'Automatic',
    'trans.manual': 'Manual',
    // Home page
    'home.hero.title': 'Find Your Dream Car',
    'home.hero.subtitle': 'Cars from European BCA Europe auctions',
    'home.hero.subtitleCount': 'Over {n} cars from European auctions',
    'home.hero.browse': 'Browse Catalog',
    'home.popular': 'Popular:',
    'home.auctions.title': 'Cars at Auction',
    'home.auctions.count': '{n} cars in catalog',
    'home.brands': 'Popular Brands',
    'home.startingPrice': 'Starting price',
    'home.km': 'km',
    'home.seeAll': 'See all cars',
    'home.recent': 'Recently Added',
    'home.recentSub': 'New lots from BCA Europe',
    'home.seeAllCars': 'All cars',
    'home.details': 'Details',
    'home.loading': 'Loading...',
    'home.noLots': 'No lots in the database yet.',
    'home.cta.title': 'Ready to buy a car from a European auction?',
    'home.cta.desc': 'Register, top up your balance, and start bidding today. We handle delivery and customs clearance.',
    'home.cta.create': 'Create account',
    'home.cta.browse': 'Browse catalog',
    'home.cta.verified': 'Verified cars',
    'home.cta.guarantee': 'Deal guarantee',
    'home.cta.delivery': 'Turnkey delivery',
    'home.how': 'How it works',
    'home.step1.title': 'Registration',
    'home.step1.desc': 'Create an account and complete verification',
    'home.step2.title': 'Top up balance',
    'home.step2.desc': 'Make a deposit to participate in auctions',
    'home.step3.title': 'Choose a car',
    'home.step3.desc': 'Find a car in the catalog or in live auctions',
    'home.step4.title': 'Place a bid',
    'home.step4.desc': 'Participate in the auction in real time',
    'home.step5.title': 'Pay for the lot',
    'home.step5.desc': 'After winning, pay for the vehicle',
    'home.step6.title': 'Delivery & customs',
    'home.step6.desc': 'We deliver and clear customs for you',
    'home.step7.title': 'Receive your car',
    'home.step7.desc': 'Pick up the vehicle at your address',
    // Catalog page
    'catalog.title': 'Car Catalog',
    'catalog.lots': 'lots',
    'catalog.filters': 'Filters',
    'catalog.reset': 'Reset',
    'catalog.brand': 'Brand',
    'catalog.allBrands': 'All brands',
    'catalog.model': 'Model',
    'catalog.modelPlaceholder': 'Start typing model...',
    'catalog.year': 'Year',
    'catalog.price': 'Price, EUR',
    'catalog.fuel': 'Fuel',
    'catalog.allFuels': 'All',
    'catalog.trans': 'Transmission',
    'catalog.mileage': 'Mileage, km',
    'catalog.engine': 'Engine capacity, cc',
    'catalog.find': 'Search',
    'catalog.loading': 'Loading...',
    'catalog.notFound': 'No lots found. Try changing filters.',
    'catalog.km': 'km',
    'catalog.ps': 'hp',
    'catalog.currentBid': 'Current bid',
    'catalog.startingPrice': 'Starting price',
    'catalog.loadingMore': 'Loading...',
    'catalog.allLoaded': 'All lots loaded',
    'catalog.from': 'From',
    'catalog.to': 'To',
    'sort.new': 'Newest',
    'sort.upcoming': 'Upcoming auctions',
    'sort.priceAsc': 'Price ↑',
    'sort.priceDesc': 'Price ↓',
    'sort.yearDesc': 'Year ↓',
    'sort.mileageAsc': 'Mileage ↑',
    // Lot detail spec labels
    'spec.power': 'Power',
    'spec.fuel': 'Fuel',
    'spec.mileage': 'Mileage',
    'spec.year': 'Year',
    'spec.transmission': 'Transmission',
    'spec.color': 'Color',
    'spec.type': 'Type',
    'spec.doors': 'Doors',
    'spec.seats': 'Seats',
    'spec.gears': 'Gears',
    'spec.volume': 'Displacement',
    'spec.emission': 'Emission',
    'spec.owners': 'Owners',
    'spec.keys': 'Keys',
    'spec.ps': 'hp',
    'spec.kw': 'kW',
    'spec.km': 'km',
    // Lot detail page
    'lot.loading': 'Loading...',
    'lot.notFound': 'Lot not found',
    'lot.backToCatalog': 'Back to catalog',
    'lot.home': 'Home',
    'lot.catalog': 'Catalog',
    'lot.noPhoto': 'No photo',
    'lot.gallery.all': 'All photos',
    'lot.gallery.exterior': 'Exterior',
    'lot.gallery.interior': 'Interior',
    'lot.gallery.damage': 'Damage',
    'lot.specs': 'Specifications',
    'lot.pending': 'Lot is being inspected by experts, info will appear shortly',
    'lot.equipment': 'Equipment',
    'lot.showAll': 'Show all ({n})',
    'lot.showLess': 'Show less',
    'lot.serviceHistory': 'Service History',
    'lot.historyDate': 'Date',
    'lot.historyMileage': 'Mileage',
    'lot.historyDesc': 'Description',
    'lot.historyCompany': 'Company',
    'lot.accident': 'Accident / Damage',
    'lot.damagePhotos': 'Damage photos',
    'lot.body': 'Body',
    'lot.interior': 'Interior',
    'lot.tires': 'Tyres / Wheels',
    'lot.tiresPosition': 'Position',
    'lot.tiresDepth': 'Tread depth',
    'lot.tiresSize': 'Size',
    'lot.stoneChips': 'Stone chips / Windscreen',
    'lot.seats': 'Seats',
    'lot.general': 'General info',
    'lot.parking': 'Parking fee',
    'lot.condition': 'Condition',
    'lot.startingPrice': 'Starting price',
    'lot.pricePending': 'Pending',
    'lot.buyNow': 'Buy now price',
    'lot.currentBid': 'Current bid',
    'lot.watching': 'watching',
    'lot.ended': 'Auction ended',
    'lot.winning': 'You\'re winning!',
    'lot.outbid': 'You\'ve been outbid',
    'lot.autobidActive': 'Auto-bid up to {n} {cur}',
    'lot.bidSuccess': 'Bid accepted!',
    'lot.processing': 'Processing...',
    'lot.makeBid': 'Place bid',
    'lot.bidFor': 'Bid for {name}',
    'lot.autoBidLabel': 'Auto-bid (Pre-bid)',
    'lot.autoBidHint': 'The system automatically outbids competitors up to the specified limit.',
    'lot.autoBidPlaceholder': 'Limit from {n}',
    'lot.autoBidSet': 'Set',
    'lot.minPayment': 'Minimum payment',
    'lot.origin': 'Made in:',
    'lot.seller': 'Seller:',
    'lot.inFavorite': 'In favourites',
    'lot.addFavorite': 'Add to favourites',
    'lot.tradingFor': 'Bidding for:',
    'lot.selectTrader': '— Select client —',
    'lot.loginPrompt': 'to place a bid',
    'lot.loginLink': 'Log in',
    'lot.bidHistory': 'Recent bids',
    'lot.autoBidTooltip': 'Auto-bid',
    'lot.brokerNotice': 'Your broker is bidding on your behalf. Add the lot to your favourites and your broker will bid.',
    'lot.minBidError': 'Minimum bid: €{n}',
    'lot.noResponse': 'No response from server. Please try again.',
    'lot.minAutoBidError': 'Auto-bid must be at least €{n}',
    // Contacts page
    'contacts.badge': 'Contacts',
    'contacts.title': 'Get in Touch',
    'contacts.subtitle': 'We\'re always available and ready to help',
    'contacts.phone': 'Phone',
    'contacts.hours': 'Working Hours',
    'contacts.hoursValue': 'Mon — Fri: 9:00 — 18:00',
    'contacts.formTitle': 'Send Us a Message',
    'contacts.name': 'Name',
    'contacts.namePlaceholder': 'Your name',
    'contacts.messageLabel': 'Message',
    'contacts.messagePlaceholder': 'Your message...',
    'contacts.submit': 'Send',
    // Reviews page
    'reviews.badge': 'Customer Reviews',
    'reviews.title': 'What <span class="accent-text">our clients</span> say',
    'reviews.subtitle': 'Real reviews from buyers who purchased vehicles through our platform. We value every opinion.',
    'reviews.promo.title': 'Promo: video review = 100 USDT',
    'reviews.promo.text': 'Record a video review with your car purchased through RB Motors in April 2026 and get a cashback of <strong>100 USDT</strong> to your balance.',
    'reviews.promo.countdownLabel': 'Until promo starts:',
    'reviews.promo.days': 'd',
    'reviews.promo.hours': 'h',
    'reviews.promo.minutes': 'min',
    'reviews.promo.seconds': 'sec',
    'reviews.promo.btn': 'Learn more',
    'reviews.loading': 'Loading reviews...',
    'reviews.totalCount': '{n} reviews',
    'reviews.leaveReview': 'Leave a review',
    'reviews.loginToReview': 'Log in to leave a review',
    'reviews.loadMore': 'Load more',
    'reviews.loadingMore': 'Loading...',
    'reviews.noReviews': 'No reviews yet. Be the first!',
    'reviews.error.load': 'Failed to load reviews',
    'reviews.modal.title': 'Leave a review',
    'reviews.modal.success.title': 'Thank you for your review!',
    'reviews.modal.success.text': 'Your review has been published successfully.',
    'reviews.modal.ratingLabel': 'Your rating',
    'reviews.modal.nameLabel': 'Your name',
    'reviews.modal.namePlaceholder': 'How should we sign you? (optional)',
    'reviews.modal.textLabel': 'Your review',
    'reviews.modal.textPlaceholder': 'Tell us about your car buying experience through RB Motors...',
    'reviews.modal.cancel': 'Cancel',
    'reviews.modal.submit': 'Publish',
    'reviews.modal.submitting': 'Sending...',
    'reviews.month.0': 'January',
    'reviews.month.1': 'February',
    'reviews.month.2': 'March',
    'reviews.month.3': 'April',
    'reviews.month.4': 'May',
    'reviews.month.5': 'June',
    'reviews.month.6': 'July',
    'reviews.month.7': 'August',
    'reviews.month.8': 'September',
    'reviews.month.9': 'October',
    'reviews.month.10': 'November',
    'reviews.month.11': 'December',
    // Auth error messages
    'auth.login.emptyFields': 'Please enter email and password',
    'auth.login.error': 'Invalid email or password',
    'auth.login.success': 'You have successfully logged in',
    'auth.login.errorGeneral': 'Login error. Please try again later.',
    'auth.register.emptyFields': 'Please fill in all required fields',
    'auth.register.passwordMismatch': 'Passwords do not match',
    'auth.register.passwordTooShort': 'Password must be at least 8 characters',
    'auth.register.error': 'Registration error',
    'auth.register.success': 'Account created! Welcome.',
    'auth.register.errorGeneral': 'Registration error. Please try again later.',
    'auth.register.telegramError': 'Telegram login error',
    'auth.login.password': 'Password',
    'auth.login.passwordPlaceholder': 'Enter password',
    'auth.callback.loading': 'Completing login...',
    'auth.callback.redirect': 'Redirecting to login page...',
    'auth.callback.blocked': 'Account is blocked.',
    'auth.callback.error': 'Login error. Please try again.',
    'auth.callback.noData': 'Authorization data not received.',
    // Dashboard
    'dash.title': 'Overview',
    'dash.loading': 'Loading...',
    'dash.error': 'Failed to load data',
    'dash.onboarding.title': 'Getting Started',
    'dash.onboarding.remaining': 'Complete {n} remaining steps for full access',
    'dash.onboarding.goTo': 'Go',
    'dash.onboarding.complete.title': 'You are ready to bid',
    'dash.onboarding.complete.subtitle': 'All steps completed — welcome to the auction',
    'dash.step.register': 'Registration',
    'dash.step.email': 'Email confirmed',
    'dash.step.docs': 'Documents uploaded',
    'dash.step.kyc': 'KYC verification',
    'dash.step.broker': 'Broker assigned',
    'dash.card.balance': 'Balance',
    'dash.card.activeBids': 'Active bids',
    'dash.card.favorites': 'Favourites',
    'dash.card.orders': 'Active orders',
    'dash.action.catalog': 'Catalog',
    'dash.action.live': 'Live bids',
    'dash.action.documents': 'Documents',
    // Balance
    'balance.title': 'Balance',
    'balance.loading': 'Loading...',
    'balance.error.balance': 'Failed to load balance',
    'balance.error.history': 'Failed to load transaction history',
    'balance.current': 'Current balance',
    'balance.verifyNotice': 'Top-up available after account verification',
    'balance.close': 'Close',
    'balance.topUp': 'Top up',
    'balance.deposit.title': 'Balance top-up',
    'balance.deposit.desc': 'Make a bank transfer using the details below and notify your manager. Funds credited within 1–2 business days.',
    'balance.deposit.recipient': 'Recipient',
    'balance.deposit.purpose': 'Payment reference',
    'balance.deposit.note': 'Include your ID in the payment reference — required for crediting funds.',
    'balance.history.title': 'Transaction history',
    'balance.history.empty': 'No transactions yet',
    'balance.history.date': 'Date',
    'balance.history.type': 'Type',
    'balance.history.desc': 'Description',
    'balance.history.amount': 'Amount',
    'balance.history.after': 'Balance after',
    'balance.type.deposit': 'Deposit',
    'balance.type.carPayment': 'Car payment',
    'balance.type.commission': 'Commission',
    'balance.type.refund': 'Refund',
    'balance.type.delivery': 'Delivery',
    'balance.type.customs': 'Customs',
    'balance.type.bidLock': 'Bid lock',
    'balance.type.bidUnlock': 'Bid unlock',
    'balance.type.other': 'Transaction',
    // Orders
    'orders.title': 'My Orders',
    'orders.loading': 'Loading...',
    'orders.error': 'Failed to load orders',
    'orders.empty': 'You have no orders yet',
    'orders.costs': 'Costs',
    'orders.carPrice': 'Car price',
    'orders.commission': 'Commission',
    'orders.delivery': 'Delivery',
    'orders.customs': 'Customs',
    'orders.total': 'Total',
    'orders.managerComment': 'Manager comment',
    'orders.timeline': 'Status history',
    'orders.timeline.loading': 'Loading...',
    'orders.timeline.empty': 'No records',
    'orders.estimate': 'Estimated date:',
    'orders.notFound': 'Lot not found',
    'orders.status.pending': 'Pending confirmation',
    'orders.status.approved': 'Approved',
    'orders.status.paid': 'Paid',
    'orders.status.deliveredSvh': 'Delivered to warehouse',
    'orders.status.customs': 'At customs',
    'orders.status.cleared': 'Customs cleared',
    'orders.status.delivering': 'In delivery',
    'orders.status.completed': 'Completed',
    // Notifications
    'notif.title': 'Notifications',
    'notif.markAll': 'Mark all as read',
    'notif.empty': 'No notifications',
    'notif.error': 'Failed to load notifications',
    'notif.delete': 'Delete',
    // Watchlist
    'watchlist.title': 'Watchlist',
    'watchlist.loading': 'Loading...',
    'watchlist.error': 'Failed to load watchlist',
    'watchlist.brands': 'Tracked brands',
    'watchlist.addBrand': 'Add',
    'watchlist.modal.title': 'Add brand',
    'watchlist.modal.search': 'Search brand...',
    'watchlist.modal.loading': 'Loading...',
    'watchlist.modal.empty': 'Nothing found',
    'watchlist.favorites': 'Favourite lots',
    'watchlist.lots': 'Tracked lots',
    'watchlist.km': 'km',
    'watchlist.startPrice': 'Starting price',
    'watchlist.watching': 'watching',
    'watchlist.empty': 'You have not added any lots to the watchlist yet',
    // Calendar
    'calendar.title': 'Auction Calendar',
    'calendar.loading': 'Loading...',
    'calendar.error': 'Failed to load calendar',
    'calendar.empty': 'No favourite lots with a scheduled auction',
    'calendar.browse': 'Go to catalog',
    'calendar.today': 'Today',
    'calendar.km': 'km',
    'cal.jan': 'January', 'cal.feb': 'February', 'cal.mar': 'March', 'cal.apr': 'April',
    'cal.may': 'May', 'cal.jun': 'June', 'cal.jul': 'July', 'cal.aug': 'August',
    'cal.sep': 'September', 'cal.oct': 'October', 'cal.nov': 'November', 'cal.dec': 'December',
    'cal.sun': 'Sunday', 'cal.mon': 'Monday', 'cal.tue': 'Tuesday',
    'cal.wed': 'Wednesday', 'cal.thu': 'Thursday', 'cal.fri': 'Friday', 'cal.sat': 'Saturday',
    // Calculator
    'calc.title': 'Customs Calculator',
    'calc.subtitle': 'Estimated customs costs for importing a car into Belarus',
    'calc.form.title': 'Vehicle parameters',
    'calc.carPrice': 'Car price (EUR)',
    'calc.year': 'Year of manufacture',
    'calc.fuelType': 'Fuel type',
    'calc.engine': 'Engine volume (cc)',
    'calc.delivery': 'Delivery (EUR)',
    'calc.company': 'Company commission (EUR)',
    'calc.calculate': 'Calculate',
    'calc.result.title': 'Final calculation',
    'calc.result.carPrice': 'Car price',
    'calc.result.customs': 'Customs duties',
    'calc.result.excise': 'Excise tax',
    'calc.result.duty': 'Import duty (10%)',
    'calc.result.vat': 'VAT (20%)',
    'calc.result.pension': 'Pension fund (3%)',
    'calc.result.totalCustoms': 'Total customs',
    'calc.result.extra': 'Additional costs',
    'calc.result.delivery': 'Delivery',
    'calc.result.company': 'Company commission',
    'calc.result.total': 'Total cost',
    'calc.result.disclaimer': '* This calculation is approximate. Exact amounts depend on the current EUR/BYN rate and individual import conditions. Contact a manager for an accurate quote.',
    'calc.result.age': 'Car age: {n} years (coeff. ×{c})',
    'calc.ph.price': 'e.g. 12000',
    'calc.ph.year': 'e.g. 2019',
    'calc.ph.engine': 'e.g. 1600',
    'calc.ph.delivery': 'e.g. 800',
    'calc.ph.company': 'e.g. 500',
    'calc.error.price': 'Please enter the car price',
    'calc.error.calc': 'Calculation error. Please try again.',
    // Traders
    'traders.title': 'My Traders',
    'traders.loading': 'Loading...',
    'traders.error': 'Failed to load traders',
    'traders.empty': 'You have no assigned traders yet',
    'traders.verified': 'Verified',
    'traders.trade': 'Trade',
    'traders.favorites': 'Favourite lots',
    'traders.add': 'Add',
    'traders.fav.loading': 'Loading...',
    'traders.fav.empty': 'No favourite lots',
    'traders.modal.search': 'Search by make, model...',
    'traders.modal.searching': 'Searching...',
    'traders.modal.empty': 'Nothing found',
    'traders.km': 'km',
    'traders.status.active': 'Active',
    'traders.status.pending': 'Pending',
    'traders.status.blocked': 'Blocked',
    // Documents
    'docs.title': 'Documents',
    'docs.upload': 'Upload document',
    'docs.loading': 'Loading...',
    'docs.error': 'Failed to load documents',
    'docs.required.title': 'Required documents',
    'docs.action.upload': 'Upload',
    'docs.action.retry': 'Retry',
    'docs.badge.pending': 'Under review',
    'docs.badge.approved': 'Approved',
    'docs.table.file': 'File',
    'docs.table.type': 'Type',
    'docs.table.status': 'Status',
    'docs.table.date': 'Date',
    'docs.tooltip.download': 'Download',
    'docs.empty': 'You have no documents yet',
    'docs.empty.btn': 'Upload first document',
    'docs.modal.title': 'Upload document',
    'docs.modal.type': 'Document type',
    'docs.modal.file': 'File',
    'docs.modal.click': 'Click to select a file',
    'docs.modal.hint': 'PDF, JPG, PNG, DOCX — up to 10 MB',
    'docs.modal.cancel': 'Cancel',
    'docs.modal.uploading': 'Uploading...',
    'docs.modal.submit': 'Upload',
    'docs.type.passport': 'Passport / ID',
    'docs.type.invoice': 'Invoice',
    'docs.type.customs': 'Customs document',
    'docs.type.poa': 'Power of attorney',
    'docs.type.other': 'Other',
    'docs.req.passport.label': 'Passport / ID',
    'docs.req.passport.desc': 'Scan or photo of the main page',
    'docs.req.poa.label': 'Power of attorney',
    'docs.req.poa.desc': 'If acting on behalf of a company',
    'docs.status.approved': 'Approved',
    'docs.status.pending': 'Under review',
    'docs.status.rejected': 'Rejected',
    'docs.type.passportShort': 'Passport',
    'docs.type.customsShort': 'Customs',
    'docs.error.fileSize': 'Maximum file size is 10 MB',
    'docs.error.upload': 'Failed to upload file. Please try again.',
  },
};

@Injectable({ providedIn: 'root' })
export class LanguageService {
  private readonly platformId = inject(PLATFORM_ID);
  readonly lang = signal<Lang>('ru');

  init(): void {
    if (!isPlatformBrowser(this.platformId)) return;
    const saved = localStorage.getItem('lang') as Lang | null;
    if (saved === 'ru' || saved === 'by' || saved === 'en') {
      this.lang.set(saved);
    }
  }

  setLang(l: Language | Lang): void {
    const code = l as Lang;
    this.lang.set(code);
    if (isPlatformBrowser(this.platformId)) {
      localStorage.setItem('lang', code);
    }
  }

  t(key: string): string {
    return T[this.lang()][key] ?? key;
  }
}
